### ISSUE TITLE
Allow user to specify multiple detectors for simulation

### ISSUE THREAD

**Issue by kadrlica** [LSSTDESC/imSim#104]
The current command line interface allows the user to specify simulation of all detectors or one detector. It would be nice to allow the user to simulate a subset of detectors. This could be achieved by simple modifications to the `imsim.py` argument parser and the compilation of the `detector_list`.

* Add `action='append'` [to the argparser](https://github.com/LSSTDESC/imSim/blob/5b815e37df98d1300e183e8a3356ee290993bd9c/bin.src/imsim.py#L33) 
* Iterate through sensors when [building `detector_list`](https://github.com/LSSTDESC/imSim/blob/5b815e37df98d1300e183e8a3356ee290993bd9c/bin.src/imsim.py#L80)

**Comment by danielsf** [comment]
Using the `gs_object_arr` will give you every object in the field of view.

The right thing to do is probably create a set that is the union of all of the `gs_object_dict[arguments.sensor]` lists you care about, making sure not to duplicate entries.  That would  be a pretty brute force loop, but won't be the biggest time suck in the whole imSim run, by any stretch.

**Comment by kadrlica** [comment]
Would this be something like:
```
gs_objects_to_draw = np.unique([gs_object_dict[s] for s in arguments.sensor]).tolist()
```
?

**Comment by danielsf** [comment]
Yeah.  That should do it.

**Comment by jchiang87** [comment]
yes, I added that feature to the multiprocessing branch to address this request.

**Comment by cwwalter** [comment]
OK closing. Thanks.
