### ISSUE TITLE
Add a flat-production script

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#120]
We should add a imSim command line option, or just a script that will solely call the sensor model with a flat background as the sky. We will need to specify an SED and the magnitude/".  

Should we produce monochromatic flats?

This should run extremely quickly.

**Comment by jchiang87** [comment]
I *think* this is the GalSim script that @rmjarvis suggested to use for making flats:

https://github.com/GalSim-developers/GalSim/blob/releases/2.0/devel/lsst/treering_flat.py

We'd need to modify it, of course, to get the pixel geometry, etc., to match the current sims of the LSST sensors.

**Comment by rmjarvis** [comment]
Yep.  That's the one I wrote to test how fast it could be to build flats.  It has a pretty extreme tree ring profile.  Not the LSST one, but I think it properly builds in the correlations from B/F.

The critical parameter that determines the fidelity of the correlated noise is counts_per_iter.  I *think* 4K for that is fine (for an 80K flat), but I didn't really do any sophisticated tests to make sure.

**Comment by cwwalter** [comment]
I guess we want something that can both make large numbers of low intensity (for flat fielding) and a few of high intensity (for BF kernel extraction).

For extracting darks etc.. we do that though the amp writing interface?

**Comment by rmjarvis** [comment]
Normally flats are high intensity.  It's much simpler to do the low intensity ones.  You don't need any loop like I do here.

**Comment by jchiang87** [comment]
> For extracting darks etc.. we do that though the amp writing interface?

Yes, essentially, but we still need a little bit of code to make an empty eimage with the desired exposure times.

**Comment by hsnee** [comment]
I took a shot at this [in this notebook](https://gist.github.com/hsnee/f875d91c191dd003397c10a22c54f355) based [on this](https://github.com/GalSim-developers/GalSim/blob/releases/2.0/devel/lsst/treering_flat.py) and I think it's outputting flats with correct pixel geometry and lsst wcs. I changed some parameters (e.g. higher counts_per_iter) to make a quick test in the notebook. Does it look right? If so, I can turn it into a scripts (+ command line option?) and do a pull request.

**Comment by jchiang87** [comment]
Thanks, Husni.  Please proceed with the pull-request.

**Comment by cwwalter** [comment]
Letting @craiglagegit know about this work.  In the end you will want to use the more complete/tree-ring model so Craig can give you guidance in the PR.

**Comment by craiglagegit** [comment]
Hi Husni,

The notebook you have looks good with the simple tree ring model.  As Chris said, you will ultimately want to use the more complex tree ring model that we built for DC2. At [this link](https://github.com/craiglagegit/ScratchStuff/blob/master/treering_flat_csl_full_30apr18.py) is the Python code I used to generate the flats in Slide 9 of [this presentation](https://confluence.slac.stanford.edu/display/LSSTDESC/January+-+June+2018?preview=/229017346/234164013/SAWG_TreeRings_BF_Lage_30Apr18.pdf).  You will want to use the most current tree ring model file, which I think is the one at [this location](https://github.com/LSSTDESC/imSim/blob/master/data/tree_ring_data/tree_ring_parameters_2018-04-26.txt). 

Let me know if you have questions.

Craig

**Comment by rmjarvis** [comment]
> You will want to use the most current tree ring model file, which I think is the one at this location.

Well, really we wan to make sure we use the **same** tree ring model as the main images are using.  @jchiang87 can probably confirm or deny if that link is the right one to use.

**Comment by jchiang87** [comment]
There's a function, `desc.imsim.add_treering_info`, in the package that should be used to update the detector objects with the same tree ring models as we use for running the sims.  The code in #126 will need a little re-working in order to use that function correctly.
