### ISSUE TITLE
Make imSim simulate comCam

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#125]
With the new camera object infrastructure in obs_lsstCam it should be possible to simulate the comCam configuration once all of the issues in #121 are addressed.  This will be an important feature in the DC3/Commissioning era.

This likely requires checking all camera information is retrieved strictly through the camera objects both in imSim and in sims_GalSimInterface.

One thing that I'm not sure is yet decided and perhaps @RobertLuptonTheGood or others can add some thoughts:

I believe the new obs_lsstCam will handle all LSST cameras.  This means that currently we have (or will soon have) comCam, auxTel, lsstCam, phoSim, and imSim.  But if we want to simulate comCam in imSim do we need a imSim_comCam? Is there extra information in the "sim cameras" not in the real cameras? Or could we in fact just use the comCam and lsstCam description?

**Comment by cwwalter** [comment]
In addition to the camera objects above, the optics will need to be separately described both parametrically (as in #122) and through optical raytracing in the new code from @jmeyers314 (tracked in #10).

imSim will need to ask for both the proper camera and optics by name. We might consider how to describe this in the config input file .

**Comment by cwwalter** [comment]
Recording information here from slack conversation with Brian Stalder.  We will need a new Batoid configuration for the ComCam.

The lenses will be different as will the filters.

Brian has a Zemax file for the comcam configuration we can look at when we need it.

**Comment by cwwalter** [comment]
Also an answer to some of the very old questions above:  

The DM Camera object we are now using in imSim will be able to load a description for the ComCam (and also LATTIS in AuxTel).

**Comment by cwwalter** [comment]
I'm attaching the ComCam Zemax config here. I have gzipped it so GitHub doesn't complain it doesn't understand the file type.

[LSST_ComCamBaseline_TeleCamUpdate1.zmx.gz](https://github.com/LSSTDESC/imSim/files/8585206/LSST_ComCamBaseline_TeleCamUpdate1.zmx.gz)

**Comment by cwwalter** [comment]
Re-upping this old issue, because now we are ready.

With the general structure of imSim we can load independent optics and camera models.  These both exist now for ComCam.

Early tests by @jmeyers314 show that with a a few minor modifications to handle input names in the telescope loader we can get reasonable looking output.

We can not yet ingest this data into a butler because (as expected) the header information is incorrect. So, some work needs to happen to:

- Make the headers correct
-  Load current/correct sensor/electronics characterization  information into the ComCam camera model.

For the purposes of this work we will assume that the optical throughput of the ComCam filters are the same as LSSTCam.  The shape differences are correctly taken into account already in the optical model and the material is supposed to be the same.  [Note: currently we don't handle interference effects etc inside of the filter.  The optical model just does bending, all the throuput is handled separately]

Please add any other issues we need to address I have missed to this issue.

**Comment by jchiang87** [comment]
It would be useful to have a time scale for this work.  The header stuff is trivial, but updating the parameters in obs_lsst for ComCam will take some effort to analyze those data and make the updates in obs_lsst.

**Comment by cwwalter** [comment]
We are going to have a hard deadline of it should really be tested before March.  There is going to be an operations rehearsal where we run the ComCam in playback mode then. So I think aiming for the end of this year would be good.

**Comment by jchiang87** [comment]
This is addressed by #433 , #448, #449, and #450.  Marking as closed.
