### ISSUE TITLE
Optical Aberration Improvements

### ISSUE THREAD

**Issue by djperrefort** [LSSTDESC/imSim#128]
While writing the wiki verification page for the aberrated optics model, it came to mind that there are a few issues within the model that were occasionally discussed but never addressed. I list them here for reference and to track future progress.

1. The PSF contribution of the optical system should be looked at for a collection of randomly
   generated optical states to ensure the results look reasonable.

2. The Zernike coefficients are currently only sampled at 35 positions in the exit pupil.
   The distribution of these points causes certain nominal effects to be undersampled.
   This can be resolved by increasing the sampling in the exit pupil

3. The distributions for each optical mode are created from a limited number of AOS simulations
   (~7). Ideally, we would like to run additional simulations to have a better sampling.

**Comment by djperrefort** [comment]
In LSSTDESC/DC2-production#259 it was pointed out that the modeled PSF's are too round. Some of this was attributed to identified bugs, but it did not fully solve the problem.

The issue mentions that the undersampling of the focal plane might effect the ellipticity of the optical PSF by introducing vertical and horizontal symmetry. In particular, the sampling points happen to be at the nodes of Z19, and the peaks/valleys of Z18 (see
https://www.telescope-optics.net/images/zernike_noll.PNG)

It was also pointed out that we might be staying too close to the nominal optical model, and we need to allow more variation in the simulated deviations. The current optical model only considers a small part of the deviations that the optical system will introduce. Since we are specifically modeling effects that are uncorrected by the closed-loop system - which handles slowly varying errors - our models are only an approximation.

As a temporary stop-gap PR LSSTDESC/imSim#164 reduces the FoV fitting function from Z4 through Z22 to Z4 through Z15. It also multiplies amplitudes of the optics misalignments by an artificial factor of 3.

**Comment by cwwalter** [comment]
This is no longer relevant since now we have our own ray-tracing.  But, this is an important historical issue because exactly how we handled this in DC2 comes up a lot.  It may also be relevant when writing papers. So, I am closing this but have added a new "Historical" label to make it easier to find in the future.
