### ISSUE TITLE
Extend DCR to non-silicon sensor configurations.

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#133]
With lsst/sims_GalSimInterface#54 DCR was added. However, currently it will only be on when the user selects a sensor model.  We should extend this to the simple pixelization case.

Functionally, there are two drawObject functions in galSimInterpreter.py.  The on with DCR is the one is the in the class GalSimSiliconInterpeter which inherits from GalSimInterpreter.  This is what is actually being used for DC2 and implements Craig's sensor model.  Rather than just cut and paste the code to the version in the base class, we may want to restructure things a bit and at least add a DCR setup function so the same code is not-duplicated.

**Comment by cwwalter** [comment]
@rmjarvis @danielsf @jchiang87 

So, now that the drawImage in the siliconClass skips the silicon model for some super faint objects I wonder if it would make sense to let the nonSilicon base class call the silicon one with a skip parameter?  That would stop the duplication of code that exists now and issues like the DCR only being currently handled in the silicon version would go away.  

Are there other reasons they should be kept separate? Speed? ...

**Comment by jchiang87** [comment]
As I've mentioned before, this code needs to be refactored.   Let's write some unit tests to be sure we can do that refactoring safely first.  I don't think it needs to happen this year.  The instance catalog redesign and handling in imSim and sims_GalSimInterface will impact a lot of the same code, so we should just wait until then to address this.

**Comment by cwwalter** [comment]
Thanks.  Sounds good.

**Comment by cwwalter** [comment]
This work will happen in the context of overall code refactoring as we change the instance catalog format and parallelization paradigm.

**Comment by cwwalter** [comment]
This work should happen naturally when the code is refactored and the code currently in sims_galSimInterface modes into imSim.  Also the galsim surface operations interface may be generalized.

**Comment by cwwalter** [comment]
I believe this now happens naturally after the refactoring. @jchiang87 please reopen if you disagree this should now work.
