### ISSUE TITLE
Backport sensor model diffusion change in GalSim to 1.6 release for use in 2.0i

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#141]
There is currently a PR into GalSim here:

https://github.com/GalSim-developers/GalSim/pull/981

being worked on by @craiglagegit and @rmjarvis.

It implements a correction/fix to the diffusion coefficient as described by @karpov-sv here:

https://github.com/LSSTDESC/imSim/wiki/diffusion_validation#model-details

which we should implement before running. 

Since the plan for 2.0i is now to try to run quickly; this will likely now happen before we upgrade the stack to GalSim version 2.   Would it be possible to get this merged and then backported to the GalSim 1.6 release series so that @danielsf could organize a new release before early to mid September to be used int he 2.0i run?

**Comment by rmjarvis** [comment]
I don't see why this change is important for DC2.  It's about a technical change in the Gaussian diffusion size, which is highly subdominant to the other sources of seeing being simulated.  This doesn't seem like an aspect of realism that is relevant to any of the science goals of DC2.

**Comment by rmjarvis** [comment]
It's definitely not a trivial amount of work to backport it.  This change is slated for inclusion in version 2.1, not even the 2.0 series.  I'd like some kind of science justification for why it is necessary, rather than just an "it would be nice" kind of argument.

In particular, I'm hard pressed to think of any test that the SAWG could do on DC2 images, where they could actually tell the difference between the two diffusion models, when there is also optics and atmospheric components to the PSF.

**Comment by cwwalter** [comment]
> It's definitely not a trivial amount of work to backport it. This change is slated for inclusion in version 2.1, not even the 2.0 series. I'd like some kind of science justification for why it is necessary, rather than just an "it would be nice" kind of argument.

OK. Sorry. I thought this was a change to the only the diffusion part and that is already in 1.6.  I didn't appreciate it was something that could also not be trivially applied there too as I was looking at the code difference described in:

https://github.com/LSSTDESC/imSim/wiki/diffusion_validation#model-details

This change basically doubles the size of the diffusion cloud, but I agree it is sub-dominant.  

If things were re-arranged such that this is not easy to do I will retarget it for later.

**Comment by rmjarvis** [comment]
The change to the code per se isn't that hard.  But every time we release a version, there is a significant amount of work to make sure everything about the release is done properly.  That's the non-trivial part.

**Comment by cwwalter** [comment]
OK, I understand.  What is your thinking now about the 2.1 release timescale schedule?

**Comment by rmjarvis** [comment]
I don't think we were planning on releasing 2.1 before the DC2 time frame.  But again, if you can make a science case for why it's important to do so sooner than later, we'll certainly consider it.

**Comment by cwwalter** [comment]
I think @jmeyers314's fix that halves the memory of the atmospheric screens is already in 2.0. Is that correct?

**Comment by rmjarvis** [comment]
Yes.

**Comment by cwwalter** [comment]
Back porting this fix won't happen for 1.6. So, we will wait until imSim is using a 2.1 series GalSim to fix the diffusion spot size.  However, this difference should be sub-dominant to the atmospheric PSF.

Given the timeline, this will happen after the 2.0 run 

Closing this issue now.
