### ISSUE TITLE
Add option to turn off the sky background.

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#144]
It would be useful to have a mode where we turn off the sky background completely.  This is particularly useful for studying things like the effect of BF on stars.

**Comment by jchiang87** [comment]
The Dark Matter group renewed a request for this feature.  I have one or two other updates I'd like to make so I'll include this with those changes.

**Comment by cwwalter** [comment]
I have this turned off now for my photon counting tests.  I found the most straightfoward way to to this off and not disturb the other things that are also calculated was to comment this out:

https://github.com/lsst/sims_GalSimInterface/blob/count_photons/python/lsst/sims/GalSimInterface/galSimInterpreter.py#L351

But, then you aren't in the imSim code and don't have straightforward access to the config file objects.  So I was waiting until we refactored things before checking a feature in for this as no one else was clamoring for it.  Just to let you know in case it is helpful.

**Comment by jchiang87** [comment]
After further discussion with @johannct , the reason for this request is to be able to inject dwarf satellite galaxies into existing DC2 images, so they need raw images to add to the DC2 raws, with effects like bias level and read noise also disabled, but effects like crosstalk, gain, etc. enabled.   I'll make a new issue on object injection to track this work.

**Comment by cwwalter** [comment]
There is also this related issue I added with DM work in mind a while ago: #109

**Comment by katrinheitmann** [comment]
Sorry for interrupting this discussion ... But I think it would be really great if we can capture requests and reason for requests and ongoing work that might be then connected to those requests more globally. Maybe it's just me, but in general, I have a hard time following all the many github issues, and if there would be one place where we collect requests including the science reason for the request in one place and then from there link relevant detailed issues, it would help me a lot. This is not just for imSim but also for e.g. the extragalactic catalog outputs, so it would be a more general procedure we could/should come up with. Thoughts?

**Comment by cwwalter** [comment]
> Sorry for interrupting this discussion ... But I think it would be really great if we can capture requests and reason for requests and ongoing work that might be then connected to those requests more globally. Maybe it's just me, but in general, I have a hard time following all the many github issues, and if there would be one place where we collect requests including the science reason for the request in one place and then from there link relevant detailed issues, it would help me a lot. This is not just for imSim but also for e.g. the extragalactic catalog outputs, so it would be a more general procedure we could/should come up with. Thoughts?

Let me see if I can incorporate this into the redesign area. I think there is some utility to keeping (e.g. imSim requests) with imSim so we don't have to go looking somewhere else. But, let's see what it actually looks like and then we can evaluate if more is needed.

**Comment by cwwalter** [comment]
This was implemented with #224.
