### ISSUE TITLE
add the option to create `raw` files directly, skipping the eimage generation step

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/imSim#146]
For Run2.0i production, we'd like to save the disk resources needed to persist the eimage files, even temporarily.  Since it's possible to integrate the conversion to `raw` files in the main simulation code, we should enable that option for Run2.0i.

**Comment by cwwalter** [comment]
This change was made in the 2.0i development work.  I will add a new issue to make the functionality more flexible.
