### ISSUE TITLE
estimate the expected runtimes of sensor-visit jobs based on the instance catalog contents

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/imSim#148]
We'll need to gather statistics from some reasonably sized sample of test runs in order to apply a regression or other analysis to make these estimates.   We should do this for different runtime configurations, but the main use case will be for the full sensor model and atmospheric PSF.    Since this would be used for DC2, we should also make sure we have representative instance catalogs to use, e.g., containing knots, static lenses, sprinkled objects (including bright foreground galaxies), etc..

**Comment by jchiang87** [comment]
Much of the info needed to understand this issue has come about as a by-product of addressing the increased resource requirements for Run2.0i as discussed at [this issue](https://github.com/LSSTDESC/DC2-production/issues/263#issuecomment-420122116) in the DC2-Production repo.
For instance catalogs larger than ~50k objects, where most of the galaxies are faint, the execution time is dominated by the fixed computational cost per object, so the runtime should scale ~linearly with number of objects for large catalogs.  Here is a plot of the elapsed time for rendering objects as a function of object number for a 460k instance catalog:
![runtime_vs_objects_drawn_fixed](https://user-images.githubusercontent.com/1994473/45570641-3dc75680-b818-11e8-8b5e-9d6c6a70498b.png)
`fast_sim` refers to running with the `--disable_sensor_model --psf DoubleGaussian` flags set, whereas both `slow_sim` and `fixed_sim` have the sensor model enabled and use `--psf Atmospheric`.  The `fixed_sim` curve results from the code optimizations described at the above DC2-production issue and implemented in this [PR for `sims_GalSimInterface`](https://github.com/lsst/sims_GalSimInterface/pull/62).  The overall speed up relative to the `slow_sims` case is a factor ~2.3, and that is largely from changes related to moving the creation of the `SiliconSensor` model and bandpass calculations outside of the loop over instance catalog objects.   Two additional changes only affect very faint objects (`flux < 10 photons`) and appear to kick in around 380k objects for this visit.  The net effect of these changes is unclear, but for the part of the curve past 380k, the relative speed up is another factor of ~1.5.

The following three panels show the time spent rendering each object for the three runs:
![time_to_draw_vs_object_num](https://user-images.githubusercontent.com/1994473/45571450-145bfa00-b81b-11e8-8cbd-c63bd613a284.png)
The objects are sorted by `magnorm` (magnitude at 500nm) by the code before the rendering starts, so the brighter objects (mostly stars) are rendered first.  For those objects, the rendering time is dominated by the number of photons (i.e., the flux) rather than the fixed cost calculations.

**Comment by cwwalter** [comment]
These parameters were used for 2.0i. Closing this issue now.
