### ISSUE TITLE
read in the object ids from the instance catalogs as strings

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/imSim#151]
Currently they are assumed to be `int`s.   Looks like there are just two lines to change:
https://github.com/LSSTDESC/imSim/blob/master/python/desc/imsim/imSim.py#L186  and line 195.

phosim already allows for string ids in `v3.7.x`, and the SNe for DC2 may have string ids.

**Comment by jchiang87** [comment]
In `sims_GalSimInterface`, this line also explicitly expects the object ids to be an `int`:
https://github.com/lsst/sims_GalSimInterface/blob/master/python/lsst/sims/GalSimInterface/galSimInterpreter.py#L599

**Comment by cwwalter** [comment]
Recording information from CWW/JC in-person conversation.

This likely will have an effect on the RandomWalk galaxies and also could affect downstream programs as the code for the object type is encoded in the lower 10 bits of the integer uniqueID.

**Comment by cwwalter** [comment]
Is this still happening, or on hold/canceled due to the other ramifications of the change? Or still needs discussion with Rahul and all?

**Comment by jchiang87** [comment]
I think we need to make this change to support the WFD SNe.  Those are the only objects that will not be cast-able as ints, so any downstream programs that read the instance catalogs will still be able to extract things like galaxy_id from the lower 10 bits.

**Comment by cwwalter** [comment]
OK.  So it will always be an added sub-string to the original uniqueID (now as a string)? We already need this for 2.0i even without the sprinkler. Is that correct?

@EiffL just flagging you on this in case it is relevant to the knot class.

**Comment by jchiang87** [comment]
> So it will always be an added sub-string to the original uniqueID (now as a string)? 

I don't know the final format but it will be something like <galaxy_id>+<sn_id> = `1000001682_MS_564_6`

> We already need this for 2.0i even without the sprinkler. Is that correct?

Yes, this is for SNe in the WFD region which will be included even with the sprinkler disabled.

**Comment by EiffL** [comment]
Argh, yes, changing the uniqueID will impact the RandomWalk (because the random seed used to sample the knots is based on the id), but that should be easy to accommodate. Just let me know if/when the change happens, and I can make sure the RandomWalk code gets properly updated

**Comment by jchiang87** [comment]
@EiffL Regarding uniqueID, the only  difference is that we'll store them as strings instead of ints, i.e., [here](https://github.com/LSSTDESC/imSim/blob/473fd8e550f4fc743dadbcc6a87b6fd284596f3f/python/desc/imsim/imSim.py#L186)
So if your knot objects continue to have ids that are cast-able as ints, the code that sets the random seed, 
https://github.com/lsst/sims_GalSimInterface/blob/4c67ec1e7e6e55df837d5630ae9b75003d68c473/python/lsst/sims/GalSimInterface/galSimInterpreter.py#L454
should be fine.

**Comment by EiffL** [comment]
agreed, it should be fine as long as the objectids cast to ints correctly

**Comment by cwwalter** [comment]
Is there a PR for this one? Or is it in the commit of some of the others? I can't find it in imSim or sims_galSimInterface..

**Comment by jchiang87** [comment]
For imSim, it's integrated in the `dc2_run2.0_rc` branch directly (2786b1fd), and there's this [PR](https://github.com/lsst/sims_GalSimInterface/pull/63) in `sims_GalSimInterface`

**Comment by cwwalter** [comment]
OK got it; thanks.  I had the centroid one, but I thought there were more. The Random knot changes are somewhere else?

**Comment by jchiang87** [comment]
The RandomWalk code isn't affected by this change since it had already cast the `uniqueId` to an `int` when passing it as a seed to the rng.  As long as the instance catalog code doesn't use uncastable string ids for the knots, no changes are needed for the RandomWalk code.

**Comment by cwwalter** [comment]
This change was made in the 2.0i development work.
