### ISSUE TITLE
Remove dependence of obs_lsstSim for geometry information.

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#156]
This is different than #121 which addresses using the camera objects to get sensor information for writing the amp files.  This work primarily involves how sims_galSimInterface gets various geometry information.

**Comment by cwwalter** [comment]
@danielsf and @jchiang87 I lost track of the status of this one.  There were some sailing tests etc which stopped previous work last I heard.  Has anything changed?

**Comment by jchiang87** [comment]
As far as I know, no new work had been done on this.   It's still an open issue.

**Comment by cwwalter** [comment]
OK. Can we live with this for DC2?  Or should we target it for changing?

**Comment by jchiang87** [comment]
I think we should just live with it for DC2.  I doubt Scott or I have time to deal with it.

**Comment by cwwalter** [comment]
OK removing not adding a DC2 label to this (but not pushing all the way to DC3).

**Comment by cwwalter** [comment]
Note: sims_galSimInterface is also depending on obs_lsstSim through its use of an LsstObservatory() object used to return telescope position with code like:

```
        observatory = LsstObservatory()
         self.fitsHeader.set('OBS-LONG', observatory.getLongitude().asDegrees())
         self.fitsHeader.set('OBS-LAT', observatory.getLongitude().asDegrees())
         self.fitsHeader.set('OBS-ELEV', observatory.getElevation())
         obs_location = observatory.getLocation()
         self.fitsHeader.set('OBSGEO-X', obs_location.geocentric[0].value)
         self.fitsHeader.set('OBSGEO-Y', obs_location.geocentric[1].value)
         self.fitsHeader.set('OBSGEO-Z', obs_location.geocentric[2].value)

```

Are there other ways to get this information?

**Comment by jchiang87** [comment]
I think the equivalent of https://github.com/lsst/obs_lsstSim/blob/master/python/lsst/obs/lsstSim/makeLsstSimRawVisitInfo.py#L37 needs to be implemented in `obs_lsst`.

**Comment by cwwalter** [comment]
Per @danielsf this work is currently planned on a June 2019 timescale.
