### ISSUE TITLE
Automatically transition to DFFTs for drawing extremely bright objects

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#157]
Currently, we have to apply a maximum brightness cut in our instance catalogs since extremely bright objects can take a very long time to draw.  So, for both PhoSim and imSim, any object with a magnitude less than 10 is replaced with a magnitude of 10.

As a certain point, it becomes faster to just do the DFFT and convolve the object with its PSF.  It would be good to smoothly and automatically make this transition.  We could either try to do it in imSim itself or, there is an older GalSim issue where making this an option in the GalSim core is discussed:

https://github.com/GalSim-developers/GalSim/issues/205#issuecomment-308005390

This change would allow us to simulate arbitrarily bright objects.  

Exactly how this would interface with the atmospheric and optical ray-tracing would need to be considered.

**Comment by cwwalter** [comment]
@rmjarvis This is something we talked about a long time ago that could help with speed on the brighter object side.  It is a GalSim enhancement, but I thought I would just bring it up on our radar again so we keep it in mind during broader conversations.

**Comment by jmeyers314** [comment]
A quick thought here: is anybody actually interested in using magnitude 10 stars for anything (6 mag brighter than saturation limit)?  If the only reason we care about these is to see their effects on other nearby objects, then maybe it's sufficient to just plop down circular Kolmogorov PSFs, or double Gaussians (anything fast and not woefully wrong); don't bother with atmosphere/optics modeling.  Maybe this is even an afterburner...

**Comment by cwwalter** [comment]
I guess one thing useful for this conversation is to write down how many objects we are really talking about here.  In general, having a mode selection where you could either choose a full DFFT or simple PSF if you cross-over a threshold sounds useful.

One other thing to keep in mind is that once we have your ray tracing working we will eventually want the option of getting ghosts etc.

**Comment by rmjarvis** [comment]
I think a simpler thing we could do is transition to is using fewer photons for the bright objects.  For very bright things, we can just bundle the photons into fewer total to be shot.  (I.e. each "photon" would carry a flux > 1.)  

I'm trying to think about how to decide when this is acceptable, but at least above saturation, I'm pretty sure we don't care about the exact profile being right.  (As Josh pointed out.)

My thought is to implement this using a max_num_photons parameter, which I'm guessing could be something like 1.e6 or 1.e7.  My understanding is that the zero point is 31, which I think means that's the magnitude of a single photon.  Mag 16 is 15 mag brighter, so 100^3 = 1.e6.  So if that's roughly where we are saturating, then there isn't much point in using more photons that this.

**Comment by cwwalter** [comment]
Note this is being discussed here:

https://github.com/GalSim-developers/GalSim/issues/994

**Comment by cwwalter** [comment]
It's not clear if this would be ready for DC2 yet but it is being actively considered now by the GalSim team.

**Comment by rmjarvis** [comment]
Ref: https://github.com/lsst/sims_GalSimInterface/pull/74
This will need some corresponding code in imSim.  @jchiang87 Let me know if you want me to try to do that too, or if you'd rather do that yourself.

**Comment by cwwalter** [comment]
Since this might go into 2.1.. Let me just double check on something:

Where does the current replacement on mag=10(?) happening and the AGN brightness cuts etc happening. I just want to understand if we are cutting them from the instance catalog first since Scott is getting started and there would be no bright objects to deal with..

**Comment by jchiang87** [comment]
@rmjarvis Please go ahead and add the needed code.

**Comment by rmjarvis** [comment]
Done. #189

**Comment by cwwalter** [comment]
Closing this issue as #189 is now merged.  @rmjarvis are all optimizations before we start DC2  (with the possible exception of partial binary instance catalog format) now complete?

**Comment by rmjarvis** [comment]
>  @rmjarvis are all optimizations before we start DC2

All the optimizations that I'd had in mind to do are done.
