### ISSUE TITLE
Enforce physical camera rotations in the cadence

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#158]
Currently we apply the rotational dithers as an afterburner by reading and adding new columns to the OpSim database (done by @humnaawan and @egawiser) .  This has the drawback that certain rotations are actually unphysical since there is a limit and hysteresis that comes from the winding and un-winding of the camera utility cables.  Currently we apply a random rotation on every filter change.

To really do this properly requires that the scheduler knows about the position of the camera as it runs through the sequence.  Eventually we should interface with the scheduler group and get a (possibly our) algorithm incorporated upstream.

**Comment by humnaawan** [comment]
@cwwalter there's work underway to fix this issue, e.g., see [here](https://github.com/lsst/sims_maf/issues/151) for an update to the MAF Stacker (which is analog of the afterburner, only now anyone can run it and add a rotational dither column to the database). Also, checkout the conversations in Slack, e.g., [here](https://lsstc.slack.com/archives/C7T3SSA1Y/p1535488721000100), for thinking beyong the current implementation of rotational dithers.

**Comment by cwwalter** [comment]
@humnaawan Thanks!

**Comment by cwwalter** [comment]
I'm actually not sure of the status of how the rotations are currently tracked ( @humnaawan and @egawiser and all might know) but, in the end I believe that this isn't a job for imSim to track.  

Tracking the state of the telescope from exposure to exposure and ensuring we never wind up in an unphysical configuration is beyond what we have the capability to do and would require a lot of work.  I think we originally added this issue as more of a global rather than imSim specific context.

This is something that should be constrained at the opsim / scheduler level I think.

I am going to close this, but feel free to discuss here.

**Comment by jchiang87** [comment]
> This is something that should be constrained at the opsim / scheduler level I think.

This is how we are handling it, i.e., using the relevant info from the opsim db, when we are using one.  This is still an issue, however, for hand-crafted instance catalogs.
