### ISSUE TITLE
Implement vignetting

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#16]
Currently,  there will be no vignetting in produced images across the focal plane.  There are several ways this could be addressed.

In a sky model (issue #5) it could manually be added or, if in that model, the light from the sky was actually raytraced through the atmosphere (issue #8) and  into the optics (issue #10) it could happen naturally.  

I think an appropriate  obscuration of the pupil in the optics FFT convolution might also naturally handle this (an expert should comment).  

This issue is just a place holder to remind us that it is an issue.

**Comment by jmeyers314** [comment]
>I think an appropriate obscuration of the pupil in the optics FFT convolution might also naturally handle this

Pupil obscuration should work for getting the vignetted PSF right, but it won't get the amplitude right in the current GalSim implementation.  (Right now the GalSim optics PSF is always normalized to unit integrated surface brightness).  I think it would be relatively straightforward to do the right thing though and scale the PSF amplitude by the area of the unobscured pupil.

**Comment by cwwalter** [comment]
This will be handled by #10 when Batoid is integrated into the code for doing optical ray tracing. In the future, we might consider a parameterized fast model built on that work but I am closing this issue now.
