### ISSUE TITLE
Model weak lensing distortions

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/imSim#17]
For `sersic2d` objects in the phosim instance catalogs, the 8th, 9th, and 10th columns (the three following the redshift) are the weak lensing distortion parameters, `gamma1`, `gamma2`, and `kappa`.  Currently, we aren't doing anything with them (and catsim doesn't set them, so they are zero in the Twinkles instance catalogs, for example).   So the `sims_GalSimInterface` code needs to be updated to make use of them, and we need to pass those parameters from the instance catalog.  Also, we need a means of filling those values in the instance catalogs given some lensing map.

**Comment by jchiang87** [comment]
@danielsf I'm going to start working on this issue.  Can you point me at where in the sims code the shear parameters can be obtained and also how that info should passed to GalSim?

**Comment by jchiang87** [comment]
It looks like changes in the `sim_GalSimInterface` and `imSim` code need to occur in four places:
* Modify [`GalSimCelestialObject`](https://github.com/lsst/sims_GalSimInterface/blob/master/python/lsst/sims/GalSimInterface/galSimCelestialObject.py#L16) to include the WL shear and convergence parameters.
* Modify [`GalSimBase.get_fitsFiles`](https://github.com/lsst/sims_GalSimInterface/blob/master/python/lsst/sims/GalSimInterface/galSimCatalogs.py#L356) to pass those parameters to the `GalSimCelestialObject` constructor.
* Modify [`GalSimInterpreter.drawSersic`](https://github.com/lsst/sims_GalSimInterface/blob/master/python/lsst/sims/GalSimInterface/galSimInterpreter.py#L355) to apply the lens model parameters to the galaxy model before convolving with the PSF.
* Modify `imSim`'s [`extract_objects`](https://github.com/LSSTDESC/imSim/blob/master/python/desc/imsim/imSim.py#L239) function to add the WL parameters to the `phosim_galaxies` dataframe.

**Comment by danielsf** [comment]
Sorry I didn't see this thread when you first posted it.  I agree that those are the changes we would need.

**Comment by cwwalter** [comment]
@jchiang87 This can be closed correct?

**Comment by jchiang87** [comment]
closed by #72
