### ISSUE TITLE
Interleave starlight for more realistic BF and  intra-object checkpointing.

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#171]
Currently, the light from objects do not impinge on the sensor simultaneously.  This has a few implications.  This is actually an approximation for the BF effect for overlapping objects as (For example) if a dim object is drawn first, and a bright object 2nd, the dim object will have no BF distortion.

One suggestion made today by @adrianpope was to image bright stars in several steps and randomize the order or drawing relative to other objects. This would, in effect, interleave the light in a way that would more realistically simulate light impinging from multiple objects simultaneously. 

It also would allow objects which took a very long time to draw to be check-pointed in the middle of their imaging, thus possibly increasing efficiency.

This has a fair amount of book-keeping implications both inside and outside of imSim since the assumption is that the same object only goes into the imaging loop once (for centroid files, checkpointing etc).

**Comment by cwwalter** [comment]
@rmjarvis Do we want to consider this in the context of #157 / https://github.com/GalSim-developers/GalSim/issues/994 or put this off for a DC3 era project?

**Comment by rmjarvis** [comment]
I don't think anything about GS #994 will address this.  Even with the changes I'm proposing there, it's still probably a good idea to interleave the really bright objects among the other objects by splitting them up to get more realistic B/F effects.  However, I also don't think this is a particularly pressing change for DC2, so I'm fine with this being pushed off to the DC3 era.

**Comment by cwwalter** [comment]
I just meant I wondered if in the process of making those changes if it would be good to account for this possibility? I could image there might be large changes to the drawing loops and it might be good to keep it in mind now.

OK let's push this to DC3 for now. Thanks.

**Comment by cwwalter** [comment]
This will be automatically handled when we have new a photon pipeline and the parallelization scheme changes so that we have pooled photons. Closing this issue.
