### ISSUE TITLE
Extend centroid file with information for faint objects

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#185]
We would like to extend the centroid file to:

- [ ] Write entries for non-flux realized objects which are skipped with a zero flux entry
- [ ] Add a column for realized in addition to calculated flux 
- [ ] Add a flag field which will include (at least) information on the class of object (skipped, simple SED, Dim, full treatment etc)

**Comment by cwwalter** [comment]
Follow on discussion with Mike and Jim.

We want to add a 32 bit integer flag for which we will set bits to specify how the object was handled.

Proposed list
Bit 0 - Normal
Bit 1 - Object Skipped
Bit 2 - Simple SED
Bit 3 - No Silicon Model
Bit 4 - Rendered with FFT

Please edit or confirm...

**Comment by jchiang87** [comment]
This work will be implemented in https://github.com/lsst/sims_GalSimInterface/pull/76

**Comment by jchiang87** [comment]
I'm wondering what "Normal" means.  If bits 1, 2, 3, and 4 are not set, is the object "Normal" by default?  Can bit 0 be set with any others also set?   If bit 0 is redundant wrt the other bits, then we should just omit it so that if the composed integer is 0, then the object is "Normal".

**Comment by cwwalter** [comment]
Sorry.. that is what I actually meant but typed too fast. I originally started with value (0,2,4) but then switched the text to bits.  So no bits: value=0 = normal.

Do you both agree?

**Comment by cwwalter** [comment]
I updated the post above with this change.

**Comment by jchiang87** [comment]
ok, thanks. That makes sense now.

**Comment by cwwalter** [comment]
This is now closed with lsst/sims_GalSimInterface#76.

As mentioned in the preflight checklist distributions of these objects is one of the things that should be checked during our tests with the production candidate before we start the main run.
