### ISSUE TITLE
Possible add new galaxy types to the parser / Galsim interface

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#19]
Currently the parser and interface only handle stars and 2d Sersics.  These were the only examples in the instance catalog I saw.  

However, there are other types in GalSim (like Gaussians and the new inclined Sersic) which could handle more PhoSim morphologies.

The full list of PhoSim spatial models is below.  Currently, all modes other than point and sersic2D are ignored.
- point (No parameters This is a model primarily used for stars, but also unresolved objects.)
- gauss (1 parameter: sigma in arcseconds This is a model for a gaussian-shaped object.)
- movingpoint (2 parameters: the derivative of the velocity arcseconds per second along the ra direction, the derivative of the velocity in arcseconds per second along the dec direction)
- sersic2D (4 parameters: half-light radius of semi-major axis in arcseconds, half-light radius of semi-minor axis in arcseconds, position angle in radians, sersic index)
- sersic (6 parameters: size of axis 1 in arcseconds, size of axis 2 in arcseconds, size of axis 3 in arcseconds, sersic index, polar angle in radians, position angle in radians)
- If the SOURCE_TYPE contains the word fits or fit,it will look for that file in the image directory; (2 parameters: pixel size (in arcseconds) and rotation angle (in degrees). RA goes to the left and DEC goes up in physical coordinates Note that PhoSim will not use the header information, because you may want to use the same image in multiple field locations)

I think the twinkles catalogs currently only contain the cases handled but others could be added in the future to this interface.  Alternatively, other types could only be handled in other interfaces.

**Comment by cwwalter** [comment]
@katrinheitmann @SimonKrughoff @evevkovacs Do you know if the output of the new catalogs will require us to describe more galaxy types than 2d sersics?

**Comment by evevkovacs** [comment]
At the moment the answer is no. However, we have been discussing with 
Scott D. here, and ultimately this will be up to the WGs to decide. If 
they need more complexity than that, they will ahve to let us know.

**Comment by cwwalter** [comment]
With the addition of random walk knots and other separate issues for galaxies from images etc I am going to close this.  If someone wants to make suggestions for other specific sources they can separately.
