### ISSUE TITLE
Implement mixed focal plane

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#221]
In the DC3 era likely want to move to a more realistic mixed focal place with both e2v and ITL sensors.  Some ability now exists to switch between the two configurations for things like BF (see some info #216) but geometry, bloom stop, etc is currently assumed to be the same for all of the sensors. 

Now that we are using obs_lsst this should be possible.

**Comment by katrinheitmann** [comment]
Wouldn't you "in real live" wait until you know how well DM can take care of this with actual data? I am not quite sure what you would want to test. If it is e.g. cosmology constraints given this as a systematic, we would really want to see how well DM can do. Or do you want to test DM for this? Is that too early? I am not sure I quite understand what you want to test yet.

On 6/25/19 2:53 PM, Chris Walter wrote:

In the DC3 era likely want to move to a more realistic mixed focal place with both e2v and ITL sensors. Some ability now exists to switch between the two configurations for things like BF (see some info #216<https://github.com/LSSTDESC/imSim/issues/216>) but geometry, bloom stop, etc is currently assumed to be the same for all of the sensors.

Now that we are using obs_lsst this should be possible.

**Comment by cwwalter** [comment]
I want to make the simulation respect the actual instrument we are building.  Of course, if DM isn't ready to handle mixed focal planes yet then we might need to wait before we run with with more than one sensor type simultaneously, but to be able to eventually do this, we need to build the ability to handle this as a basic level in the code.   

One of the basic tests from the SAWG group (that was requested in the Berkeley session and elsewhere) was to test how good our sensor models were for the two cases.  We will have lab data on this (plus sky data from the AuxTel with ITL) and we currently don't have a simple way to switch between two (non-hybrid) configurations.  We mostly have one model hard coded in.  We also need this to compare our models against that data (in simulation of spots and flats etc).  With that we can also run smaller tests and see how things would look different on the sky with the two different sensors.

The main thing this issue is  about is adding the ability to know about and instantiate more than one type of sensor in the code infrastructure now as part of the imSim redesign we are doing. We should build it in from the beginning.

Is that helpful at all?

**Comment by katrinheitmann** [comment]
Yes, very much so, thanks! Just to recap, you are not planning at this point to do a major campaign with this implemented to test cosmological uncertainties due to this possible systematics but rather try to understand how best to implement the modeling itself. Correct?

**Comment by cwwalter** [comment]
> Yes, very much so, thanks! Just to recap, you are not planning at this point to do a major campaign with this implemented to test cosmological uncertainties due to this possible systematics but rather try to understand how best to implement the modeling itself. Correct?

Yes, that's correct.  Right now I am focused on the code infrastructure and also sensor modeling and resulting differences on smaller test sets.

For us to eventually be able to see how this changes cosmological uncertainties as part of a major campaign we need to do this work now.  Actually how and when we do that would be part of a bigger decision/discussion.  But, I do want to make sure we are ready when we decide it is time.

**Comment by jchiang87** [comment]
@cwwalter I think we can close this.  The current code simulates the mixed focal plane layout that's read from obs_lsst.

**Comment by cwwalter** [comment]
OK great, closing now.
