### ISSUE TITLE
Chunk_size handling in trim.py ignores --numrows

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#226]
Due to code that was later added to trim.py, the --numrows functionality no longer works.

The relevant code is here:

https://github.com/LSSTDESC/imSim/blob/master/python/desc/imsim/trim.py#L215

due to the range(chunk_size), that many lines will be read in once you are in the loop. The default chunk_size value is 30,000.  

This can be addressed at the same time as the input generator work in #201.

**Comment by jchiang87** [comment]
closed by #227
