### ISSUE TITLE
Allow or ignore missing phosim instance file commands

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#23]
Some valid phosim instance file commands (like rotskytel) are not in the list of valid commands.

imSim should either use these, or more gracefully ignore them.  The current behavior results in a exception.

Also allowing commenting out lines with a '#' should be supported.

**Comment by jchiang87** [comment]
I think "gracefully" ignoring things like this is what caused problems with the Run1.1 phosim output wrt the `altitude` keyword.  IMO, having things fail loudly with an exception helps make certain that the input parameters and required parameters are the same.  I think the real issue is deciding what parameters are *required* and which are *optional*.  The current test in the code imposes a 1-1 onto mapping, i.e., all the ones listed are required and no optional ones allowed.

**Comment by cwwalter** [comment]
OK fair enough.  It means we can't run with certain files but you are saying that all twinkles file would be missing this keyword?

Commenting out is still important no matter what.

**Comment by jchiang87** [comment]
I agree on commenting out.  I had to add rotskytel by hand to use imsim.  not sure why it wasn't in those files.

**Comment by danielsf** [comment]
What is rotskytel?  I know about rotskypos and rottelpos.  I have never heard of rotskytel.

**Comment by cwwalter** [comment]
I mistyped .  The one that caused the problem was rotskypos.  But they both do exist.

Look here:

https://bitbucket.org/phosim/phosim_release/wiki/Instance%20Catalog

under Telescope Operator.

**Comment by cwwalter** [comment]
Forget it... I was just reading too fast.

That one doesn't exist. Just a typo.

**Comment by jchiang87** [comment]
rottelpos was the one I had an issue with.  and this was using old instance catalogs from Run1.1.  So the most recent ones from catsim may have rottelpos.

**Comment by danielsf** [comment]
I agree with Jim's statement.  If new InstanceCatalogs don't have rottelpos, let me know, because they should

**Comment by jchiang87** [comment]
This is mostly handled by #35.   Possibly left to do:

- [ ] Make list of required phosim commands configurable rather than hard-wired.

**Comment by danielsf** [comment]
I think this is done.  `parsePhoSimInstanceFile` reads all of the header entries in the InstanceCatalog and just emits a warning if any optional parameters are present.
