### ISSUE TITLE
Store full wcs with the output files

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#246]
The WCS representation stored in the FITS headers (we use tan-sip) is an approximation, incapable of storing the full transform needed to also represent perturbations from perfect sensor placement on the focal plane.  (CC and thanks to  @SimonKrughoff )

After having a student need this full information this week, and talking to @matroxel about tests needed both now and in the future related to WFIRST, shear tests, etc., we should also endeavor to store this full wcs in some binary way in the fits file.  Currently one could reconstruct such a WCS by fitting the output in the centroid file but this is an awkward solution.

As discussed with @rmjarvis, @jchiang87 and @jmeyers314, when we are using Batoid we may want to project a set of stars down to the focal plane and fit a wcs to those positions on an exposure by exposure basis for inclusion with the exposure.  The version being stored in the header now is an approximations to the full transform. This issue is a reminder to also store the full wcs if we find an approximation is still necessary.

**Comment by rmjarvis** [comment]
The GalSim WCS api is pretty general.  It supports essentially any mapping from (x,y) to (ra, dec).  For instance, there is a GalSim wrapper for Gary's pixmappy solution, which includes tree rings and other complex (very not FITS WCS) components, so it can handle pretty complex mappings.

Therefore, I'd suggest that it would make our lives easier in the long run it we target  making the ImSim solution to this be a subclass of `galsim.CelestialWCS`.

**Comment by rmjarvis** [comment]
cf. http://galsim-developers.github.io/GalSim/_build/html/wcs.html#celestial-wcs-s

Also, here is a comment to developers explaining what functions need to be implemented in the subclass to get it to work:
https://github.com/GalSim-developers/GalSim/blob/releases/2.2/galsim/wcs.py#L2164

**Comment by jmeyers314** [comment]
What's the purpose of this WCS?  If it's to be able to visualize raw images in ds9, then using a `galsim.CelestialWCS` wouldn't work I think.  Even if it's to jump start the stack astrometry, I imagine DM'd rather depend on Tan-SIP or some other registered fits WCS convention than depend on GalSim for this.

Also, can @SimonKrughoff elaborate on why a Tan-SIP doesn't work?  I'm certainly not an expert, but reading through the spec https://fits.gsfc.nasa.gov/registry/sip/SIP_distortion_v1_0.pdf I can't see why sensor placement perturbations would be a problem.

**Comment by cwwalter** [comment]
> Also, can @SimonKrughoff elaborate on why a Tan-SIP doesn't work? I'm certainly not an expert, but reading through the spec https://fits.gsfc.nasa.gov/registry/sip/SIP_distortion_v1_0.pdf I can't see why sensor placement perturbations would be a problem.

I'll leave this technical tan-sip discussions to others.  This was not something I heard before.  But, it is true that the wcs we write as a tan-sip is an approximation. Here is the code @jchiang87 pointed me to that does it:

https://github.com/lsst/sims_GalSimInterface/blob/4a3cf5e43474f59205eefdb34bbd2374f2a9b9fd/python/lsst/sims/GalSimInterface/wcsUtils/ApproximateWCS.py#L40

For usage: We would still have the tan-sip for ds9 and are normal usage etc. in the header. This would be an extra full GalSim wcs that would be used to check images against truth locations, make sure we can register images between WFIRST and LSST, perfectly line up images which should be the same other than changes in configuration etc.

In principle, at least some of these will always be OK if things are working properly, but it can act as a check in those cases, and seems to be necessary in the multi-instrument case.  @matroxel should say more.  He has several use cases. In pixel space we do this now with the centroid file. I came across this last week when an undergraduate doing a project found that the true ra, dec locations on the sensor via the wcs were rotated relative to the stars actually were:

<img width="813" alt="Screen Shot 2020-04-28 at 11 30 04 AM" src="https://user-images.githubusercontent.com/5562740/80506559-c63e3080-8943-11ea-81a0-891e74b4591a.png">

We switched to working in pixel space via the centroid file but that might not always be possible or convenient.

**Comment by jmeyers314** [comment]
Thanks for usage explanation.  I'm not opposed to storing both a TAN-SIP and a (non-registered) higher-fidelity representation of the WCS.

I am surprised that the TAN-SIP performance in that particular image isn't better.  Feels more like the WCS fitter failed to converge than that TAN-SIP lacks enough freedom to do the fit.  Missing by just a rotation in particular I think means the CD matrix is slightly wrong (by a small angle rotation matrix).  Is the rotation miss the same at all radii?

**Comment by SimonKrughoff** [comment]
To be clear, I was just referring to the approximate WCS that comes per focal plane from the pointing model.  TAN-SIP is fine for a per chip WCS as well, but you need a different set of coefficients for every detector.

**Comment by cwwalter** [comment]
> I am surprised that the TAN-SIP performance in that particular image isn't better. Feels more like the WCS fitter failed to converge than that TAN-SIP lacks enough freedom to do the fit. Missing by just a rotation in particular I think means the CD matrix is slightly wrong (by a small angle rotation matrix). Is the rotation miss the same at all radii?

It looks like currently only the the sky transform and the parameterized optics is considered. So, it is done once for exposure and misses any perturbation in sensor placement on the focal plane.  In practice, so far this has worked for us because it seeds the astrometric solution which eventually replaces the wcs on a per sensor basis.  But, if you try to check using sky coordinates on a visit before astrometry (instead of using the centroid file) you will see something like this.

**Comment by cwwalter** [comment]
Where do we stand with this?

@jmeyers314 is the batoid WCS written out now? Should it be?

**Comment by rmjarvis** [comment]
Nope.  We only write out the TAN-SIP approximation.  But I think that approximation should be better now than what you showed above.  In fact, since the above TAN-SIP solution wasn't so great, I wonder if that's the explanation for the failing regression tests issue that we closed earlier today.  Certainly the unit tests of the code we use to do the TAN-SIP fit in GalSim test the accuracy much more precisely than this.

**Comment by cwwalter** [comment]
Just to confirm: Is it the TAN-SIP approximation to the Batoid WCS we are now writing?

**Comment by rmjarvis** [comment]
Yes.

**Comment by cwwalter** [comment]
OK great.  Yes, I would imagine that would fix the problem above since in the situation before the parameterized WCS didn't account for aberrations, sensor location etc and this should.

I'm go to close this for now.  If anyone disagrees feel free to re-open.

**Comment by jmeyers314** [comment]
> Nope. We only write out the TAN-SIP approximation. 

Isn't the batoid WCS exactly the TAN-SIP approximation?  From this line: https://github.com/LSSTDESC/imSim/blob/main/imsim/batoid_wcs.py#L406

Or is there an additional approximation made somewhere?

There is a slight systematic in that WCS - it's constructed from chief rays only, and the chief rays land at a slightly different focal plane position than the mean of all surviving rays.

**Comment by rmjarvis** [comment]
It depends on what you mean by "batoid WCS" I guess.  But yes, that's the thing we use for all WCS things now.  In principle, there is a more precise version implicit in batoid ray tracing, but we aren't using it.
