### ISSUE TITLE
Consider how to refactor the lsst-galsiminterface library and how it relates to this code.

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#25]
Currently, some routines in the interface library  are monkey patched here in order to separate the source input mechanism from the GalSim interface code itself.

We should consider the class layout more generally and the relationship between this driving code and the library.  We can also drive other sorts of lookups (e.g. CatSim directly) but perhaps other things might use the library too.

This is a placeholder just to remind us this is an issue.

**Comment by cwwalter** [comment]
Jim and Scott met at SLAC this week to discuss the strategy to do this.

**Comment by jchiang87** [comment]
This is still open.  Scott and I agreed that we should proceed with his plan from the DESC meeting, but I wanted to wait until after DC1 production to work on it again.

**Comment by jchiang87** [comment]
This was addressed by #95.
