### ISSUE TITLE
Properly handle ELGs

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#252]
It's not clear the exact place for handling this, but emission line galaxies are important to some groups.

**Comment by cwwalter** [comment]
I think this is now handled with the SED handling if the underlying SED (like the Diffsky ones) have ELGs.  

Is that correct @jchiang87? If so we can close.

**Comment by cwwalter** [comment]
@jchiang87 Can this one be closed?

**Comment by jchiang87** [comment]
Sure, closing.
