### ISSUE TITLE
Investigate WCS regression test discrepancies

### ISSUE THREAD

**Issue by rmjarvis** [LSSTDESC/imSim#262]
As part of the imSim 2.0 refactoring, we have switched from an LSST sims WCS to using Batoid for the WCS.  We have some good unit tests that confirm this is accurate to much better than 1 arcsec for most uses, but when comparing to old outputs (using the LSST WCS code) there are discrepancies at the level of up to ~10 arcsec in some cases.

For the tests in test_batoid_wcs.py, some tests are set to tolerances of 5 arcsec.  And in test_instcat_parser.py, some required  10 arcsec tolerances.  These tests are marked with XXX to flag them as items of concern.

This issue is to try to track down the reason for this discrepancy, since the underlying algorithm we are using in Batoid should be much more accurate than this.  It seems likely that this is due to well-understood differences, e.g. in the camera layout, which has changed to accommodate the hybrid focal plane (the old spec was uniformly ITL).  Possibly other changes as well, so this may all be fine and just an error in the logic of the regression test.

However, it does raise a slightly nagging worry (for me at least) that there may be something we are missing in the new code, which was done correctly in the old code.

I think ideally, the regression tests should be testing that the new code can reproduce the old results when given the old physical parameters.  This might require some mocking of the LSST camera object to coerce it to act like it did at some point in the past.  If we can determine all the physical parameters we need to adjust to make things work out, it would give additional confidence that the new code is correct when running on the current physical parameters specified in the LSST camera object.

**Comment by jmeyers314** [comment]
Looked into this some more.  For the test_batoid_wcs.py, I got the tolerance down to 2.5 arcsec from 5 arcsec by taking the camera from `lsst.obs.lsst.LsstCam().getCamera()` and replacing the E2V sensors with ITL ones (centered at the same coordinates).  The residual quiver plot goes from

![WCS diff](https://user-images.githubusercontent.com/3650485/146237204-aefd8135-68c6-42b9-a21c-3c8a6651ba97.png)

to 

![WCS_diff2](https://user-images.githubusercontent.com/3650485/146237225-4729b7a8-3de8-44c9-bb65-176b46fa685a.png)

I don't think we're likely to do better given the residuals are pretty uncorrelated at this point.

As for the [wcs test in test_instcat_parser.py](https://github.com/LSSTDESC/imSim/blob/main/tests/test_instcat_parser.py#L219), I'm pretty sure this is a new test.  At least, I don't see anything comparable in the [v1.0 tag of this file](https://github.com/LSSTDESC/imSim/blob/v1.0.0/tests/test_instcat_parser.py).  AFAICT in fact, the `InstCat` columns being compared against are not modified by the wcs at all, but just copied straight from `self.phosim_file`.  I.e., the 10 arcsec discrepancy is just the maximum difference between [truth_stars.txt](https://github.com/LSSTDESC/imSim/blob/main/tests/data/truth_stars.txt) and [phosim_stars.txt](https://github.com/LSSTDESC/imSim/blob/main/tests/data/phosim_stars.txt).

I don't know the history of these two files, but if I had to guess I'd say the coords in `phosim_stars.txt` probably had the [deprecession magic](https://github.com/lsst/sims_catUtils/blob/ab59eb09eb3122acd3df71c06423684376afd3a9/python/lsst/sims/catUtils/mixins/AstrometryMixin.py#L417-L421) applied to them and the coords in `truth_stars.txt` haven't.

**Comment by rmjarvis** [comment]
You're right that those specific lines in the test are new.  But they were attempting to recapitulate the tests that are now blocked off by `if 0:` just above them.  The previous test required the lsst.sims package, so this was trying to do something that would test the same facts about the positions.

But looking at that test now, I see that it's testing agreement as <0.0005 radians, which turns out to be 100 arcsec.  So I guess the new test isn't any less accurate than previously.  If anything it might be 10x more accurate.

**Comment by jmeyers314** [comment]
>they were attempting to recapitulate the tests that are now blocked off by if 0:

Ah, okay.  I didn't appreciate that.  I'll have to dig to figure out exactly what `pupilCoords` are.  It still looks to me like `InstCat` isn't actually using the wcs to manipulate any ra/decs though, so I _think_ that part of the new test is broken.

> I see that it's testing agreement as <0.0005 radians

I think it 0.0005 arcsec?
```python
dd = arcsecFromRadians(dd)
self.assertLess(dd, 0.0005)
```

**Comment by rmjarvis** [comment]
Ah, you're right.  I somehow missed the arcsecFromRadians line.

**Comment by cwwalter** [comment]
Hi Mike and Josh,

Is this now OK with our latest test suite? If so, can you close?

**Comment by jmeyers314** [comment]
I'm not sure we really ever nailed this.  But I also don't envision spending significant time on it in the future.  FWIW, I don't believe there are any serious problems with our current handling of the WCS.

**Comment by rmjarvis** [comment]
Sure.  If there are problems with the WCS treatment, someone will report a bug down the line.  And if so, that bug will likely provide a better case to diagnose what is wrong than investigating this regression test further.  ;-)
