### ISSUE TITLE
imsim_bandpass normalisation

### ISSUE THREAD

**Issue by matroxel** [LSSTDESC/imSim#270]
I think this line should have a step function of width 1 angstrom instead of 1 nm. cc @rmjarvis @cwwalter 

https://github.com/LSSTDESC/imSim/blob/c6f97ba39f05313570d15671f2b9eb9bd1de24bc/imsim/instcat.py#L71

**Comment by jmeyers314** [comment]
Looks like it's more of a triangle than a step.  Why would 1 angstrom (or 0.5 angstrom, 2 angstrom, etc...) be better?

**Comment by rmjarvis** [comment]
Mostly it's to try to match what was done in DC2.  Presumably the total area was supposed to be an equivalent width of 1 A, rather than 1 nm.  This makes a difference to the normalization.  I don't know the pedigree of this choice though.

**Comment by cwwalter** [comment]
Yes, this code was originally in the old photUtils and was ported over to the new code (by Jim?)

You can see the original steps sizes here:

https://github.com/lsst-sims/legacy_sims_photUtils/blob/e14a2668a4f874f85074a8d2fc1e37654b70b5be/python/lsst/sims/photUtils/PhysicalParameters.py#L15

Which is used in 

https://github.com/lsst-sims/legacy_sims_photUtils/blob/main/python/lsst/sims/photUtils/Bandpass.py

When talking to Troxel about this during the afternoon, I confirmed may suspicion that this is matched to the SEDs in our SED library that was used with this code (originally with PhoSim).  For example in .. sims_sed_library/2017.01.24/galaxySED/Exp.40E08.25Z.spec.gz

we have 

```
500.900 0.992029
501.000 0.997241
501.100 0.995095
501.200 0.986511
501.300 0.972410
501.400 0.957695
501.500 0.949418
501.600 0.947578
501.700 0.946965
501.800 0.949724
501.900 0.950031
502.000 0.961373
```

recall that the normalization is done at 500 nm following in the PhoSim instance catalog format.

**Comment by jchiang87** [comment]
> Yes, this code was originally in the old photUtils and was ported over to the new code (by Jim?)

Nope, wasn't me.

**Comment by cwwalter** [comment]
Hmm...  OK, I think I recall we just decided to rewrite the things we were using in PhotUtils with GalSim functions, so perhaps Mike added this in the original config version and didn't refer to the old code and 1nm seemed reasonable?

**Comment by jmeyers314** [comment]
Matching what was done in DC2 is good enough for me.  I was mostly curious if this was a proposed solution to some larger problem, since I don't think changing this from 1 nm to 1 A could have a big effect.  It'd only change the calculated flux for an SED with a significant 2nd derivative over this 2 nm range I think.

**Comment by rmjarvis** [comment]
Wait, why doesn't the equivalent width matter?  I thought this could cause a factor of 10 change in the flux normalization.

**Comment by jmeyers314** [comment]
I think the way it works is the same bandpass gets applied to the object spectrum and the reference (AB) spectrum (as part of the withZeropoint call).  So the integral is ~10x smaller in both and divides out.

**Comment by jmeyers314** [comment]
```python
bp1 = galsim.Bandpass(
    galsim.LookupTable([499,500,501],[0,1,0]), 
    wave_type='nm'
).withZeropoint('AB')

bp2 = galsim.Bandpass(
    galsim.LookupTable([499.9,500,500.1],[0,1,0]), 
    wave_type='nm'
).withZeropoint('AB')

rband = galsim.Bandpass("LSST_r.dat", wave_type='nm')

sed = galsim.SED("CWW_E_ext.sed", wave_type='A', flux_type='flambda')

print(sed.withMagnitude(20.0, bp1).calculateFlux(rband))
print(sed.withMagnitude(20.0, bp2).calculateFlux(rband))
```

yields

```
0.009194459617614894
0.009194447480895405
```

**Comment by rmjarvis** [comment]
Ah good.  This isn't a bug then.  Just a (slightly) different choice.  Thanks Josh!
