### ISSUE TITLE
Errors should be raised if no objects are found for a CCD

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/imSim#285]
If there are no objects from the input catalogs that are potentially on a CCD for rendering, then error messages should be printed (or an exception raised?) to anticipate downstream failures.

For instance catalogs, this is [the relevant line of code](https://github.com/LSSTDESC/imSim/blob/3edf18c23048ec68911e88c655177b4560a52c7b/imsim/instcat.py#L212), and for skyCatalogs, it's [this line](https://github.com/LSSTDESC/imSim/blob/36b730f7bfab0eaf450c7ce6678042d2a5cb5b65/imsim/skycat.py#L53).

**Comment by g-braeunlich** [comment]
Should we actually raise an `galsim.config.SkipThisObject` exception instead of a `RuntimeError`?
Or can this somehow be handled in galsim?
If yes: how could galsim figure out (or could be notified about) the number of visible objects?
