### ISSUE TITLE
Dead link in the sphinx docs

### ISSUE THREAD

**Issue by g-braeunlich** [LSSTDESC/imSim#296]
This affects [doc/validation/diffusion.rst](doc/validation/diffusion.rst) and the wiki docs.

`diffusion_fe55_fits.png` seems to be missing (wiki ref is in https://github.com/LSSTDESC/imSim/wiki/diffusion_validation#validation-criteria, just below the table)

**Comment by jchiang87** [comment]
That link referenced the figure location from before those files were all moved to https://github.com/LSSTDESC/imSim.wiki.git.  I've include the figure directly from the wiki repo.

**Comment by cwwalter** [comment]
Thanks Jim.

Can we close this @g-braeunlich ?

**Comment by g-braeunlich** [comment]
As far as I can see, this only has gone into the wiki.
This worries me a bit because now wiki and docs diverged again and we again have the content duplicated.
My suggestion would be to move the "doc" part to the docs, removing this part from the wiki.

**Comment by g-braeunlich** [comment]
Update: the only difference seem to be the image. So I ll copy this image to the docs.
Still: I would recommend to drop the "Matrix" section of the wiki, as this is now all in docs.

**Comment by g-braeunlich** [comment]
Opened a MR: https://github.com/LSSTDESC/imSim/tree/296-dead-link-in-the-sphinx-docs

**Comment by cwwalter** [comment]
Almost no one seem s know about the wiki/matrix.  So, just think of it as a source of moving stuff into the docs now.

**Comment by g-braeunlich** [comment]
OK. So if one of the two of you (@jchiang87 or @cwwalter ) could have a look at the MR (the only thing which I added on top of the changes in the wiki is a caption of the image. Do you think it is appropriate?).
I need an approval to merge it and close the issue.
