### ISSUE TITLE
stamp.py: if branch with undefined variables

### ISSUE THREAD

**Issue by g-braeunlich** [LSSTDESC/imSim#299]
In [stamp.py](imsim/stamp.py), `LSST_SiliconBuilder.draw()`, there is an `if` branch with undefined vars `full_bounds` and `image_pos`:

```py
        if method == 'fft':
            # When drawing with FFTs, large offsets can be a problem, since they
            # can blow up the required FFT size.  We'll guard for that below with
            # a try block, but we can minimize how often this happens by making sure
            # the offset is close to 0,0.
            if abs(offset.x) > 2 or abs(offset.y) > 2:
                # Make a larger image that has the object near the center.
                fft_image = galsim.Image(full_bounds, dtype=image.dtype)
                fft_image[image.bounds] = image
                fft_offset = image_pos - full_bounds.true_center
```

**Comment by rmjarvis** [comment]
Guess that means we don't have any tests that hit that branch.  I can't remember what the impetus for this check was in the old version of this code, from which we copied this over.  Probably @jchiang87 knows?  But for now I guess you can probably just remove this.  Or maybe turn it into a warning, so we can revisit it if something ever causes it to hit this condition.

**Comment by jchiang87** [comment]
I don't recall the reason for this test.  Changing it to a warning seems reasonable.
