### ISSUE TITLE
update instance catalog parsing code to handle all possible object descriptions

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/imSim#31]
The final columns in the `object` lines of an instance catalog contain the parameters for the spatial model and for the rest frame and Galactic extinction.  According to the [phosim documentation](https://bitbucket.org/phosim/phosim_release/wiki/Instance%20Catalog), the extinction entries can have four forms:

1. `<internal dust model> iA_v iR_v <Galactic dust model> gA_v gR_v`
2. `none <Galactic dust model> gA_v gR_v`
3. `<internal dust model> iA_v iR_v none`
4. `none none`

where the choices for dust model are `CCM` or `calzetti` and the `A_v`s and `R_v`s are the model parameters, and `none` means that no dust model is to be applied.  In practice, only 1. and 2. will appear, but owing to a bug, CatSim currently writes the Galactic entry before the internal one; and the code now in imSim only handles cases that _look like_ 1. and 3. and [assumes that ordering](https://github.com/DarkEnergyScienceCollaboration/imSim/blob/5724abf72967df3537dd724199821c575ea3be82/python/desc/imsim/imSim.py#L186).  Since CatSim will presumably soon be fixed, the parser code should be updated to handle all four cases with the correct ordering. Twinkles instance catalogs for Run3 already have the fix applied.

The `spatial_pars` columns can have 0, 1, 2, 4, or 6 columns depending on the source type, so those columns should also be handled correctly.  The current imSim code only handles `point` and `sersic2d` models.

**Comment by danielsf** [comment]
The fix to CatSim is just awaiting a code review, fyi. The next release will contain it.

**Comment by jchiang87** [comment]
closed by #36
