### ISSUE TITLE
Applying vignetting to FFT-rendered objects

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/imSim#323]
Since FFT-rendered objects are not ray-traced, vignetting isn't applied by batoid.   These are usually bright stars that saturate and produce bleed trails, but some are bright galaxies.  An approximation would be to scale the object fluxes by the same vignetting function that's applied to the sky background.

**Comment by cwwalter** [comment]
@g-braeunlich @jmeyers314 Here is the previous issue for vignetting FFT objects.

**Comment by cwwalter** [comment]
@jchiang87 I think you merged this PR (and made a new issue). Is that correct? If so then go ahead and close.

**Comment by jchiang87** [comment]
closed by #368
