### ISSUE TITLE
Rotate photon velocities from focal -> pixel

### ISSUE THREAD

**Issue by jmeyers314** [LSSTDESC/imSim#328]
Around [here](https://github.com/LSSTDESC/imSim/blob/main/imsim/photon_ops.py#L344) there's a transformation of photon position from focal plane coords to pixel coords.  We should, but current don't, do something similar for the photon velocities.

**Comment by cwwalter** [comment]
Josh, I am wondering if this was done?

Your link now points to a decorator for the photon operation factory list.

**Comment by jmeyers314** [comment]
I don't think this has been done.  Current link should be something like https://github.com/LSSTDESC/imSim/blob/main/imsim/photon_ops.py#L471-L475 (but who knows how long that'll stay valid :))
