### ISSUE TITLE
Error with tests/test_photon_ops.py when run in Docker image

### ISSUE THREAD

**Issue by stuartmcalpine** [LSSTDESC/imSim#331]
One of the CI tests looks to be failing when run in the Docker image, something new in the LSST image or did I miss an update to the CI?

Log for the job here https://github.com/LSSTDESC/imSim/actions/runs/4599467200/jobs/8124871263

`=========================== short test summary info ============================
FAILED tests/test_photon_ops.py::test_config_rubin_diffraction - AttributeError: 'NoneType' object has no attribute 'info'
FAILED tests/test_photon_ops.py::test_config_rubin_diffraction_without_field_rotation - AttributeError: 'NoneType' object has no attribute 'info'
FAILED tests/test_photon_ops.py::test_config_rubin_diffraction_optics - AttributeError: 'NoneType' object has no attribute 'info'
FAILED tests/test_photon_ops.py::test_config_rubin_diffraction_optics_without_field_rotation - AttributeError: 'NoneType' object has no attribute 'info'
FAILED tests/test_photon_ops.py::test_config_rubin_optics - AttributeError: 'NoneType' object has no attribute 'info'
============= 5 failed, 86 passed, 4 warnings in 490.59s (0:08:10) =============
Error: Process completed with exit code 1.`

**Comment by jchiang87** [comment]
fixed by #333
