### ISSUE TITLE
Check spelling/validity of confirmation file entries.

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#341]
Currently, a misspelled/wrong yaml file entry will just be ignored.  This has caused some confusion and mistakes by users during testing.

@rmjarvis told us in a meeting that there is defined a straightforward way to check if entries are proper/well formed.

We should do this if we can.

**Comment by rmjarvis** [comment]
[This](http://galsim-developers.github.io/GalSim/_build/html/config_process.html#galsim.config.CheckAllParams) is the function that checks that all parameters are valid.  It's automatic if using [`GetAllValues`](http://galsim-developers.github.io/GalSim/_build/html/config_process.html#galsim.config.GetAllParams), but we can run it manually if everything is parsed manually.  
[Here](https://github.com/GalSim-developers/GalSim/blob/35bb6a03a0f7c03454e783f109f4e2b8d2bf6838/galsim/config/photon_ops.py#L232) is an example of how to use it in practice.

**Comment by cwwalter** [comment]
Classes missing parameter check linting now are:

- OpsimDataLoader
- TreeRings
- Checkpointer
- Stamp.py (non-diffraction parts)

We need to convert these to catch input mistakes.

**Comment by cwwalter** [comment]
Closed by #387.
