### ISSUE TITLE
Don't require OpsimMeta

### ISSUE THREAD

**Issue by jmeyers314** [LSSTDESC/imSim#349]
Currently some ImSim modules require having an `OpsimMetaDict` input object to function.  These include: `RubinDiffraction` (to get altitude/azimuth), `SkyCatalogLoader` (just for the band), `LSST_SiliconBuilder` (for airmass, seeing and band), `LSST_CCDBuilder` (for various things that get written to the output FITS headers like mjd, seqnum, hastart, ...)

To use any of these features, you must specify either an instance catalog file with requisite parameters, or an OpSim sqlite database.

Toting around an almost-empty instance catalog or sqlite file to run simple things like "put one star at the center of each CCD" is clumsily indirect when all of the required parameters would easily fit within the yaml config file itself.

So I propose to make it a rule that ImSim _never requires_ `OpsimMetaDict`; all of the necessary parameter passing should also be possible in the class itself.  E.g., I ought to be able to specify the band for a sky catalog within the config file, and then if it isn't present, fall back to OpsimMetaDict.

**Comment by rmjarvis** [comment]
Agreed.  In fact, with the exception of LSST_CCDBuilder, which gets a lot of things from OpsimMeta, I think we should sever any kind of explicit connection between the type and the OpsimMeta object.  The user should specify e.g. the band any way they want in the config.  And our default config file shows how to get it from the opsim_meta_dict input object.

And for LSST_CCDBuilder, I laid out a suggestion [here](https://github.com/LSSTDESC/imSim/pull/348#issuecomment-1577377827) that I think is workable to let the user specify header values directly if they want, but revert to using OpsimMeta if there is one available.  Furthermore, I think the final backup plan could be to skip those header items but emit a warning that the output files won't be usable by the DM processing unless either the opsim input is available or all relevant values are specified.

**Comment by rmjarvis** [comment]
By the way, we could also maybe consider removing the Meta part of this class name as part of this issue.  I believe it's a relic of the phosim instcat files, where this was the meta information at the top of the file before all the object information, which connected back to the opsim data.

In the now usual case of using an opsim.db file, there is nothing particularly meta about it.  It would probably be clearer to just call it an OpsimDict.
