### ISSUE TITLE
Add surface figure errors as optional output

### ISSUE THREAD

**Issue by jmeyers314** [LSSTDESC/imSim#352]
It'd be nice to write out the figure errors of each surface produced by the FEA and AOS inputs as an optional output for reality checks.

**Comment by cwwalter** [comment]
Josh is this a short or long term wish?  Should it be included in the immediate 2.0 milestone?

**Comment by jmeyers314** [comment]
I think this is fairly straightforward to implement, so let's make it a 2.0 milestone.

**Comment by cwwalter** [comment]
OK.

**Comment by rmjarvis** [comment]
Done in #372
