### ISSUE TITLE
Update FILTER keywords to conform to recent LSSTCam updates

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/imSim#363]
There are a few `FILTER*` header keywords in LSSTCam raw data that are used to construct the `physical_filter` metadata value that raw files are registered with in a data repository.  See [DM-38882](https://jira.lsstcorp.org/browse/DM-38882).

In order to ingest and process our raw files with current LSST code, we need to update these header keywords.

**Comment by cwwalter** [comment]
Should this be closed by #371?
