### ISSUE TITLE
Check to make sure we are passing focal plane position to GalSim

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#37]
This issue comes from a conversation @craiglagegit and I had today at PACCD.  In the the new GalSim code for the sensors, the angle for the photons are drawn from a distribution for the f1.4 beam before propagation into the silicon.

Currently, the code assumes you are and the center of the focal plane.  When we call GalSim from imSim we actually know the global position on the focal plane.  So, if that information gets passed along it should be possible to use an appropriate distribution.

**Comment by cwwalter** [comment]
Could @rmjarvis just clarify how this works now.  I think the angles are currently drawn from a f1.4 beam profile, but the angle does not depend on where you are in the focal plane. Is that correct?

**Comment by rmjarvis** [comment]
Yes, the photon angle sampler that is there now can draw from an annulus of an f1.4 beam (or any f/ratio) with an arbitrary central obscuration.  It doesn't take into account where the object is in the focal plane.  But this is modular, so the hook is in place if someone wants to write something more sophisticated that does take into account focal plane position.

**Comment by cwwalter** [comment]
OK, thanks.  How large an effect should the position dependence be? As you move off the center the angle of the cone should change right?  Has this been estimated or checked in the past?

**Comment by rmjarvis** [comment]
I guess the most obvious effect is vignetting.  As you get to the edges, part of the annulus is blocked by the edges of the telescope, so the incident flux goes down in proportion to the solid angle that can actually see the sky.  So doing this right would also be able to get vignetting right as well.  But aside from this, I don't know of any estimate of how large an effect it is.

I suppose a simple test someone could do with what is there now is to turn on and off the existing direction code and see how big an effect **that** makes.  The next order adjustment to get the annulus to shift around would presumably be an even smaller effect.

**Comment by cwwalter** [comment]
Got it, thanks.

**Comment by cwwalter** [comment]
With the new raytracer in #10 we should know the angle of the f1.4 beam profile.  I'm closing this for now.  We will need to interface the optical ray-tracer to the silicon photon list and this information could be passed.

In the future we may think about a fast parameterized model based on the full model.
