### ISSUE TITLE
Warn if atm_psf.doOpt is true and using RubinOptics

### ISSUE THREAD

**Issue by jmeyers314** [LSSTDESC/imSim#376]
We don't want to simulate the optics twice!  This is a bit pernicious since the default for doOpt is true: https://github.com/LSSTDESC/imSim/blob/main/imsim/atmPSF.py#L111

**Comment by rmjarvis** [comment]
+1  And probably should switch the default to False.  That feels like the wrong default behavior.

**Comment by rmjarvis** [comment]
Done in #380
