### ISSUE TITLE
Handle proper motion when interfacing with the skyCatalogs

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#381]
Reference catalogs like Gaia now have proper motion.

In the past the instance catalogs had positions which were adjusted for the time of the observation. But, currently this functionality does not exist when we are using the skyCatalogs.

We should add the functionality in imSim (and if necessary in the skyCatalog) API, so implement both proper motion and parallax for stars.

**Comment by jchiang87** [comment]
I think this functionality should live entirely in skyCatalogs.  We pass the observation time to skyCatalogs when querying the interface for the objects to render, and for objects with time varying SEDs, skyCatalogs returns the appropriate SED for that observation time.  It can just do the same for time dependent ra, dec values.

**Comment by cwwalter** [comment]
Thanks. Yes, this sounds right.  Also, this way every past and future interface (instance catalogs, other text or binary based input files) will be on the same page and need to do the same thing.

Since things like asteroids will also need to move hopefully some of this could be centralized.

**Comment by jchiang87** [comment]
Proper motion for Gaia stars is handled in this [skyCatalogs PR](https://github.com/LSSTDESC/skyCatalogs/pull/52).

**Comment by jchiang87** [comment]
The [skyCatalogs PR](https://github.com/LSSTDESC/skyCatalogs/pull/52) was merged so closing this.
