### ISSUE TITLE
Properly account for focal plane sensor height variations.

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#405]
At the PCW, @jmeyers314 tagged non-uniformities in focal plane height as one of the image quality drivers we are not currently simulating.  In the AOS group, this has also been tagged as a potential interesting way to study issues in the science sensors.

To do this, we need height variations to be encoded in the camera model so we can read them.  @RobertLuptonTheGood said in the meeting that there was an old ticket to address this issue in DM.  It sounds like the data exists but work needs to be done to make it available.

**Comment by RobertLuptonTheGood** [comment]
The DM height-of-CCD ticket is https://jira.lsstcorp.org/browse/DM-8889

**Comment by jmeyers314** [comment]
Yeah, we closed that ticket after implementing the constant height per ccd version.  I do have Andy R's surface maps, we could make a new ticket to add those in.

**Comment by cwwalter** [comment]
We now have a CCD height maps for the LSSTCam.  I'm closing this and making a new ticket for adding in ComCam height maps.
