### ISSUE TITLE
improve handling of instance catalog edge cases

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/imSim#41]
`imsim.py` responds ungracefully when certain instance catalog edge cases are encountered:

- [ ] No `object` entries at all.
- [x] objects with type `sersic2d` but no `point` entries

**Comment by cwwalter** [comment]
@jchiang87 Is this still an issue?

**Comment by jchiang87** [comment]
yes.

**Comment by cwwalter** [comment]
@jchiang87 Was this at least partially addressed by the recently closed #67 ?

**Comment by jchiang87** [comment]
only partially.  if there are no objects at all, imsim.py still crashes in an unhelpful way.

**Comment by cwwalter** [comment]
@jchiang87 does imsim.py still crash in a non-helpful way if there are zero objects after the refactor?

**Comment by jchiang87** [comment]
It doesn't crash in master any longer, it just ends without producing any output.   I've added a log message in the `multiprocessing_treering_atm_merge` branch indicating that no objects were read in if there are no objects in the instance catalog, so feel free to close this if you want.
