### ISSUE TITLE
Database concurrency issue when using Gaia stars

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#429]
If you use Gaia stars though the skyCatalog interface it accessed a database through a butler.  

With 205 sensors in a focal plane if you try to simulate several focal planes at a time, it overwhelms the database. The information should instead be read in once on a per focal plane basis.

**Comment by jchiang87** [comment]
This has been addressed in skyCatalogs: https://github.com/LSSTDESC/skyCatalogs/pull/90
