### ISSUE TITLE
Consider class-level variables for attributes in common among object types

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/imSim#43]
Currently, attributes like `.PSF` and `.noise_and_background` for the `ImSimStars` and `ImSimGalaxies` class are instance-level variables, though they should likely be the same for all object types.  Making these class-level variables would enforce that, but the `GalSimBase` class in `sims_GalSimInterface` would need to be modified.

**Comment by cwwalter** [comment]
This should probably be merged with #25.

**Comment by jchiang87** [comment]
This is no longer relevant given Scott's refactoring.
