### ISSUE TITLE
missing conda installation requirement

### ISSUE THREAD

**Issue by esheldon** [LSSTDESC/imSim#437]
I followed conda instructions here:  https://lsstdesc.org/imSim/install.html

It uses the requirements file `etc/standalone_conda_requirements.txt`

The code crashes due to missing yamlinclude, which means the requirements file needs `pyyaml-include`

**Comment by cwwalter** [comment]
I believe this is something that is new in skyCatalog  and underdevelopment (not actually imSim).  We should update the installation to instruct everyone to use a released skyCatalog version (and eventually when we understand all new requirements update that too including in cvmfs)

Erin, try, putting skyCatalog at

v1.6.0rc2

**Comment by esheldon** [comment]
Yes using that version works

**Comment by cwwalter** [comment]
Closing this issue.

**Comment by esheldon** [comment]
I think we might need to reopen this.  There is a critical bug fix going in for skyCatalogs so we will want to go beyond `v1.6.0rc2` and use the newest bug fix.   Would you be open to adding `pyyaml-include` to the requirements now?

https://github.com/LSSTDESC/skyCatalogs/pull/102

**Comment by jchiang87** [comment]
The most recent tag of skyCatalogs, v1.7.0rc4, removes the need for `pyyaml-include`.  The current `ci.yaml` uses that version now.

**Comment by esheldon** [comment]
thanks
