### ISSUE TITLE
Sky background calculation using rubin_sim.skyBrightness SEDs should not include atmospheric absorption

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/imSim#453]
There's a thread in [slack](https://lsstc.slack.com/archives/C01JTSDV7CH/p1710367626198229?thread_ts=1710347138.892389&cid=C01JTSDV7CH) where Lynne Jones mentions this and references [SMTN-002](https://smtn-002.lsst.io/#skynote), particularly footnote 1.

**Comment by cwwalter** [comment]
I'm just putting this here for future reference in case anyone is confused by why this is an issue or needs a reminder of the issue.  As Jim says this is explained in the tech note above.

Fundamentally the sky model comes from a model from ESO which is measured light coming *from* the sky including airglow etc. So the light is leaving the atmosphere and going into the pupil. Therefore it doesn't make sense to include the extinction going *through* the atmosphere.

**Comment by jchiang87** [comment]
Fixed in #470
