### ISSUE TITLE
Make the Sky model vary over the focal plane

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#46]
Issue #5 implemented the ESO sky model.  However, now the level is set solely by the pointing at the center of the focal plane.

The code should be modified to vary per chip and then per pixel.  This probably means refactoring the code to recalculate the sky level in a healpix map once outside of the chip loop.

**Comment by dkirkby** [comment]
How is `skyModel.ESOSkyModel.addNoiseAndBackground()` being called in the current simulations?  Once per chip, or once per focal plane, or something else?  I suspect that tabulating the sky model on a healpix map will be more trouble than it is worth, given that it is straightforward to evaluate the sky level directly at the center of each chip (or pixel).

**Comment by jchiang87** [comment]
once per chip.

**Comment by jchiang87** [comment]
If we want a healpix map of the sky brightness for a given set of observing conditions, e.g., read in from an instance catalog, I think it makes more sense just to provide a separate application that provides that rather than build one routinely in the `imsim.py` runs on a per-visit basis.

**Comment by fjaviersanchez** [comment]
@jchiang87 I am kind of confused. So imSim calls this function (in the current implementation) once per chip but supplies the `pointingRA` and dec from the center of the focal plane?

**Comment by jchiang87** [comment]
Yes, it's just that the original implementation didn't do the per chip coordinate calculation that Bela is adding.

**Comment by dkirkby** [comment]
> but supplies the pointingRA and dec from the center of the focal plane?

No, it gets the pointing from `self.obs_metadata`

**Comment by fjaviersanchez** [comment]
yes, but `self.obs_metadata` contains the center of the focal plane and not per-chip

**Comment by belaa** [comment]
What would be the most sensible output in this case? Should it give the sky level per chip by passing a new parameter to `skyModel.ESOSkyModel.addNoiseAndBackground()`, or should it simulate the whole focal plane and then each chip can be queried separately?

**Comment by cwwalter** [comment]
Thanks all, and thanks for the original work on this @belaa!
