### ISSUE TITLE
Validate the dark sky level.

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#47]
Issue #5 implemented the ESO sky model.  The absolute value of the dark sky in the red band seems reasonable.  With version 0.1.0 it is 438 electrons for a 15 second exposure.

This can be compared with https://github.com/lsst-pst/syseng_throughputs/blob/master/plots/table2
Where the value in r for a dark sky for 30 seconds is:  796 which corresponds to a 15 second level of 398.

However, there are some discrepancies with the PhoSim calculation.  For this previous history of this comparison please see issue #5.

This issue should be closed when we are confident that this discrepancy is understood.

**Comment by cwwalter** [comment]
When the DC1 output becomes available we should double check that the level is correct.  @fjaviersanchez could I assign you to do this as currently the function comes from you and David (see issue #45)?

**Comment by cwwalter** [comment]
@fjaviersanchez and all: Do you agree that we know what the correct sky level should be and we see that in imSim or 'fixed' PhoSim now? If so can we close this?

I opened this when we were seeing the differences with what we now know was the PhoSim bug.  We now understand that discrepancy.  But, it's good to be able to say the absolute value is correct.

**Comment by fjaviersanchez** [comment]
I would say that for average conditions the model and imSim converge but I still need to check the exposures with very high and very low sky-brightness.

**Comment by fjaviersanchez** [comment]
I checked the mean background measured by DM and OpSim's skybrightness and for dark nights I think we are fine. For bright nights there is a lot of scatter but it looks like the measured background is higher than expected

![image](https://user-images.githubusercontent.com/13971732/30837701-a9bb81ea-a21b-11e7-90fd-47c5cd77fd22.png)

The green line is `796.2*10**(-0.4*(skybrightness-21.2))` The value 796.2 comes from here: https://github.com/lsst-pst/syseng_throughputs/blob/master/plots/table2

**Comment by cwwalter** [comment]
OK thanks.  So, if you think the imSim output is consistent with our expected sky level from the project please go ahead and close this.

**Comment by fjaviersanchez** [comment]
@cwwalter @danielsf @jchiang87 @SimonKrughoff I have a question: Does OpSim provide the skybrightness at the pointing position or at a fixed position? I am asking because for this case: `{'filter': 'r', 'raft': '2,0', 'sensor': '2,0', 'visit': 2039491}` The measured background by the stack is: `11931.9617802` and the predicted background given OpSim's sky-brightness is `1597.82024901`. Also when you take a look at the image I'd say that the background is like half of that:

![image](https://user-images.githubusercontent.com/13971732/30993521-4041c332-a464-11e7-9019-130aeeaedefc.png)

You can check the raw eImage here: `'/global/cscratch1/sd/descdm/DC1/rerun/DC1-imsim-dithered/eimage/v2039491-fr/E000/R20/eimage_2039491_R20_S20_E000.fits.gz'`

Any clues?

**Comment by cwwalter** [comment]
> @cwwalter @danielsf @jchiang87 @SimonKrughoff I have a question: Does OpSim provide the skybrightness at the pointing position or at a fixed position?

I'm also going to ask @rhiannonlynne.  I thought it returns it at the pointing position.

I'm a  bit confused by this question compared to above.  Are you saying on average it is the same, but there are some cases where it is really off?

**Comment by cwwalter** [comment]
Note, that the input (for imSim) is the OpSim pointing.  But the sky level itself for imSim is set by @yoachim 's sky model. That takes a MJD and a pointing.  So, it doesn't actually know what a particular OpSim brightness is.  In PhoSim it has it's own sky model.

Is OpSim using it now to calculate the brightness? That would make sense but I am not sure of the current status.

**Comment by rhiannonlynne** [comment]
Opsim is using sims_skybrightness to calculate the sky brightness now (i.e. opsim v4, coming soon), but was not in the current set of tier1 runs (i.e. the minion_1016 generation). However, the skybrightness it predicted at a given pointing, in the given filter, should not have been that far off except during twilight, I don't think. 

Note that the minion runs carried two different skybrightness values - vSkyBright and filtSkyBrightness. These are both at the pointing position.

**Comment by fjaviersanchez** [comment]
Thanks! I will check imSim's model. I am using filtSkyBrightness to compute the values that's why I was surprised.

**Comment by fjaviersanchez** [comment]
Using the imSim's sky model in the dithered positions from `minion_1015_sqlite_new_dithers` with this snippet:

```def get_sky_mag(obsHistID,moon_ra,moon_dec,verbose=False):
        obs_md = gen.getObservationMetaData(obsHistID=obsHistID,boundLength=3)[0]
        from lsst.sims.utils import _getRotSkyPos                                
        dithered_rot_tel_pos_name = 'ditheredRotTelPos'                          
        dithered_rot_tel = obs_md.OpsimMetaData[dithered_rot_tel_pos_name]       
        obs_md.pointingRA = np.degrees(obs_md.OpsimMetaData[dithered_ra_name])   
        obs_md.pointingDec = np.degrees(obs_md.OpsimMetaData[dithered_dec_name]) 
        if verbose:                                                              
            print obs_md.pointingRA, obs_md.pointingDec                          
        dithered_rot_sky = _getRotSkyPos(obs_md._pointingRA,                     
                                                 obs_md._pointingDec,            
                                                 obs_md, dithered_rot_tel)       
        obs_md.rotSkyPos = np.degrees(dithered_rot_sky)                          
        if verbose:                                                              
            print obs_md.pointingRA, obs_md.pointingDec, np.degrees(obs_md._pointingRA), np.degrees(obs_md._pointingDec)
        skymodel.setRaDecMjd([obs_md.pointingRA],[obs_md.pointingDec],obs_md.mjd.TAI,degrees=True)                      
        xmoon = np.sin(moon_dec)*np.cos(moon_ra)                                                                        
        ymoon = np.sin(moon_dec)*np.sin(moon_ra)                                                                        
        zmoon = np.cos(moon_dec)                                                                                        
        xtel = np.sin(obs_md._pointingDec)*np.cos(obs_md._pointingRA)                                                   
        ytel = np.sin(obs_md._pointingDec)*np.sin(obs_md._pointingRA)                                                   
        ztel = np.cos(obs_md._pointingDec)                                                                              
        dist = np.sqrt((xtel-xmoon)**2+(ytel-ymoon)**2+(ztel-zmoon)**2)                                                 
        return skymodel.returnMags()['r'], dist     ```

And instead of using 'BGMEAN' I use the clipped median of the background image as a measurement for the background. I think that's the major improvement.

![screen shot 2017-10-03 at 1 19 01 pm](https://user-images.githubusercontent.com/13971732/31147309-49266cf4-a83e-11e7-9baf-a0940edb1b4e.png)

And this is using OpSim's sky-brightness instead of imSim's:

![screen shot 2017-10-03 at 1 32 43 pm](https://user-images.githubusercontent.com/13971732/31147756-b36a6dbc-a83f-11e7-8bd6-a1a3ab402208.png)

I am more satisfied with these results and I think this is pretty much ready to go but I still don't know whether I am doing something wrong to get the pointing position/skymodel or not. @danielsf @jchiang87 @cwwalter @rhiannonlynne Am I missing something?

**Comment by sethdigel** [comment]
I don't know anything, but this
`dist = np.sqrt((xtel-xmoon)**2+(ytel-ymoon)**2+(ztel-zmoon)**2)`
looks a bit odd, as the tel and moon coordinates are direction cosines.  The angular distance between the moon and the telescope pointing direction would be np.arccos(xtel * xmoon + ytel * ymoon + ztel * zmoon).

**Comment by fjaviersanchez** [comment]
@danielsf I defined them as `dithered_ra_name = 'randomDitherFieldPerVisitRA'` and `dithered_dec_name = 'randomDitherFieldPerVisitDec'`. @sethdigel: You are totally right!

**Comment by danielsf** [comment]
Okay.  That should be fine.

Pursuant to Seth's comment, if you don't want to have to worry about when `arccos` starts to diverge, `lsst.sims.utils` has methods `angularSeparation` and `_angularSeparation` (the former in degrees; the latter in radians) that thinly wrap `palpy`'s methods for finding the angular distance on the sky between two points.  It should be pretty safe against trigonometric shenanigans.

**Comment by sethdigel** [comment]
Thank you @danielsf.  The arccos does not diverge but it is not a very good way to evaluate small angular separations.  That probably does not matter a whole lot here, given the size of the moon, but what you have in lsst.sims.utils absolutely sounds better.

**Comment by cwwalter** [comment]
Reading above, I'm still a bit confused by the status of making a conclusion on this.

**Comment by fjaviersanchez** [comment]
I think this is understood now and we'll check for issues like this in DC2 as well.
