### ISSUE TITLE
set GalSimBase.allowed_chips to restrict FITS files that are produced

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/imSim#50]
For cases where the `--sensor` option is specified for `imsim.py`, we should set the `allowed_chips` attribute to a list containing the chip name:  https://github.com/lsst/sims_GalSimInterface/blob/master/python/lsst/sims/GalSimInterface/galSimCatalogs.py#L168

**Comment by cwwalter** [comment]
So the way this works now, we remove sources not on sensors from the source list when we build the dataframe right? 

What is the effect of also adding them to this list?  Is it related to light coming from sources on other sensors (the buffer variable in PhoSim)?

**Comment by jchiang87** [comment]
> So the way this works now, we remove sources not on sensors from the source list when we build the dataframe right?

Yes.

> What is the effect of also adding them to this list? Is it related to light coming from sources on other sensors (the buffer variable in PhoSim)?

The effect should simply be to omit writing the FITS files for any sensors not on that list.  Files for the sensors not in that list *could* otherwise be written out if the sims code inferred that some light from sources located on adjacent chips could land on those sensors.  @danielsf can describe the details of that inference.

**Comment by danielsf** [comment]
The relevant method is here

https://github.com/lsst/sims_GalSimInterface/blob/master/python/lsst/sims/GalSimInterface/galSimInterpreter.py#L129

For each object, it generates a postage stamp of that object, finds all of the pixels with more than 0.001 of the maximum pixel's flux, and then checks which detectors overlap with those "active" pixels.

**Comment by cwwalter** [comment]
So, if we wanted to select just single sensors, but still have them "properly" reflect flux from adjacent sources we wouldn't want to do this. Is that correct?

**Comment by danielsf** [comment]
The GalSimCatalog carries around a list of detectors to simulate.  Setting `allowed_chips` truncates that list of detectors.  Whenever the GalSimInterpreter draws a source, it uses `findAllDetectors()` to loop over the detectors in the list of allowed detectors and figure out which of those detectors might conceivably receive light from the source.  So: any chip that is in `allowed_chips` can still receive light from sources on adjacent chips.  Put another way, using `allowed_chips` does not interfere with the ability of adjacent sources to illuminate the chips you have specified.

**Comment by jchiang87** [comment]
otoh, we do down-select the instance catalog based on the chip name:

https://github.com/LSSTDESC/imSim/blob/master/bin.src/imsim.py#L69

so if we want to allow for fluxes from nearby sources not "on" a chip according to the `chipNameFromRaDec` function, we'll need to do something different....unless that function also uses that 0.001 max pixel flux method.

**Comment by danielsf** [comment]
The method that @jchiang87 referenced does not do anything clever about bright sources illuminating neighboring chips.

What we could do is use `pixelCoordinatesFromRaDec()` and force the `chipName` kwarg to be the chip we are interested in.  This will return the pixel coordinates of the objects as if they were actually on our chosen chip, even if they aren't.  Sources that are not on the chip will return pixel coordinates that go above or below the usual [0, 4000] range for x and y pixel coordinates.  We could then only keep objects whose pixel coordinates are in some reasonably expanded range (e.g. [-500, 4500]) to make sure that we keep neighboring sources that might illuminate the chip.  This, of course, will do nothing for extra bright sources that cast a very large footprint.

If we want to try to reproduce what PhoSim does, I coded up this method

https://github.com/lsst/sims_integrated/blob/feature/SIM-2112/write_end2end_scripts/python/lsst/sims/integrated/createPhoSimCatalogs.py#L88

to try to down-select InstanceCatalogs for only objects that would survive PhoSim's `trim.cpp` step.

The arguments are

name_list -- a numpy array of chipNames representing the actual result of `chipNameFromRaDec` for your sources

xpix0 -- a numpy array of x pixel coordinates for sources as if they were on the R:22 S:11 chip

ypix0 -- same as xpix0 for the y pixel coordinate

magnitude -- a numpy array of PhoSim magNorms for the sources

target_name -- the name of the chip for which you are actually making an InstanceCatalog

center -- a tuple containing the TAN_PIXEL coordinates target_name in R:22 S:11 pixel coordinates system

It returns the result of numpy.where (a list of indexes corresponding to your list of sources) representing the sources that would survive PhoSim's `trim.cpp` for the chip specified by target_name

I haven't had a chance to test it, yet, but this is what I think we would have to do to recreate PhoSim's trim step.

**Comment by cwwalter** [comment]
@jchiang87 Is the trim_instcat you just added in imsim_deep_pipeline based on the comment above by Scott?  Or is is something different/simpler?

**Comment by jchiang87** [comment]
It's a lot simpler.  It runs C++ code that filters the instance catalogs based on an acceptance cone on the sky, so if I give it the chip center and some minimal radius, it will filter out almost all of the objects not landing on the chip.   It uses streams to process the instance catalog files, so its memory footprint is very small (as opposed to reading all the objects into a data frame), and it's pretty fast.  When I was feeding the full focalplane instance catalog into the imsim parser, it was using 10s of GB of memory and crashing on some platforms.

**Comment by cwwalter** [comment]
OK. Thanks.  I guess in PhoSim, really the trim step is also a separate executable too even though they are all run by the python driver step.  So in principle this could be kept separate and then just made smarter.

Does that mean you are not using the sensor restriction in imsim.py itself now?

**Comment by jchiang87** [comment]
It's unclear whether we want to use that option or not.  We might want to revise how it works, actually.  Currently it runs chipnamefromradec to assign chipnames to each object and filters on the selected sensor.  If we apply an acceptance cone using the new trim code, then we can skip that chipname selection in the code, but I think we might still want to set the `allowed_chips` list so that only the desired chip is written out as a FITS image.

**Comment by jchiang87** [comment]
closed by #55
