### ISSUE TITLE
Add tree rings with different orientation/centers per sensor

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#59]
@craiglagegit Has shown that he can put tree rings into this Poisson simulation and they add linearly to the BF distortions.  However, we cannot pre-calculate all possible tree-ring orientations.  We need to have a template that can oriented (randomly?) and be added to the BF area distortions in the GalSim module. 

It has been suggested we could just do this with a WCS (as apparently DES does). However, our correction will rely on WCS and we would rather implement this in the model itself. 

This is one of the items on the checklist for a validated sensor model in #7.

**Comment by cwwalter** [comment]
There is another issue that needs to be considered.  In the sensors there are guard rails near the edges that also produce lateral fields and cause extra astrometric shifts at the edges. 

In the current Poisson and GalSim interpolated version of the code we don't/can't account for this since those pixels are different than the others.  In the shorter term we can get around this by masking (which people like @rhl often advocate anyway) but we may want to use more area than we would nominally mask.

It seems to me there are three approaches that could be taken:

1. Basically make a second set of "tree rings" that are added but only on edge sensors. However these effects are larger than the tree rings and simply adding them like Craig showed you could do for tree rings may not work.

2.  Make special "edge brighter-fatter" pixel runs which could be used when necessary.

3. As @mjarvis suggested handle the whole thing in a WCS.  In this comment he shows this being done in the DECam.
 
https://github.com/GalSim-developers/GalSim/issues/675#issuecomment-303441912

I am pretty reluctant to do this though since I am afraid we will build a trivial correction if we put the result in and take it out with a WCS.

**Comment by jchiang87** [comment]
Here's a finely-grained list of tasks that are needed for DC2:

- [ ] Incorporating the BNL-measured tree ring data
  - [ ] Formatting the several ITL data files into some compact format.
  - [ ] Running flat simulations to bootstrap the desired normalization.
  - [ ] Assign tree ring locations to each sensor.
- [ ] Support software
  - [ ] Set tree ring data file in the imsim config file.
  - [ ] Find the right place in the code to read in the data for imsim to use.
