### ISSUE TITLE
Add realistic electronics chain.

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#6]
Add the electronics readout to the e-image files.   Must understand how this interfaces with GalSim-developers/GalSim#799 (mid-layer API for drawImage).

**Comment by jchiang87** [comment]
I think the most straight-forward way to do this would be to either operate on the eimage files produced by `imsim.py` or operate on the full sensor GalSim Image object that the catsim code generates.  So, I don't think the electronics readout code needs to use the new mid-layer API.

**Comment by cwwalter** [comment]
OK, I understand; good.

I think the best is if we have options in the main command file to either write e-image only, both or amplifier only.

Also, I think we should try to write this like the real CCS controller output (at least on the test stands).  Is that a MEF file?  PhoSim is not doing that now.

**Comment by cwwalter** [comment]
I wanted to add here (and maybe it should be a separate issue) that we should generate any files describing the layout etc from a version controlled database.  I know such a thing exists but I don't know the details of where it lives and what exactly it describes.  I think I remembering hearing it comes from Andy R.?  @SimonKrughoff can you comment?

**Comment by tonytyson** [comment]
SLAC is releasing a new version of this momentarily.

**Comment by jchiang87** [comment]
Could you elaborate on this @tonytyson ?  I know that http://ls.st/lca-13381* is set to be approved, but I don't think that's what Chris has in mind.

The project has discussed, at least since the JTM in Phoenix in 2014, about having a query-able  database with proposed "as-built" parameters describing the focal plane layout down to the pixel level, including which types of sensor are in each slot, but I don't think that ever came to fruition.  If it does exist, then I wholeheartedly agree that we should use it.

**Comment by tonytyson** [comment]
yes, that's what i meant.

**Comment by cwwalter** [comment]
> The project has discussed, at least since the JTM in Phoenix in 2014, about having a query-able database with proposed "as-built" parameters describing the focal plane layout down to the pixel level, including which types of sensor are in each slot, but I don't think that ever came to fruition. If it does exist, then I wholeheartedly agree that we should use it.

Yes, this is what I meant.  I believe @SimonKrughoff and @connolly have both mentioned this to me.  @tonytyson do you mean a new version of the query-able database is about about to be released from SLAC?

**Comment by jchiang87** [comment]
@cwwalter Here are the focal plane descriptions from Andy R.: https://docushare.lsstcorp.org/docushare/dsweb/View/Collection-1577

These are a collection of spreadsheets and `.h` files with the focal plane geometry down to the pixel level.  John uses these files to generate the phosim segmentation.txt and focalplanelayout.txt files.  We could use these files from Andy, but it's not an optimal solution, imo.

**Comment by cwwalter** [comment]
Ah... I see. 

Well, as a stop-gap Pandas has a good xls interface mode (I have used it for teaching/gradebook related things).  So we could still write a program which programmatically gets values and then later if it becomes avaliable replace it with the database query version.

Does John just read these and then manually input values?

**Comment by jchiang87** [comment]
There must be some script that John uses, but I don't know the details.

**Comment by cwwalter** [comment]
(forgot to write above): Assuming segmentation.txt and focalplanelayout.txt is the way we want to encapsulate this information (is it?) it sounds like we should be generating those files elsewhere (in Andy's system?) and then using released versions both here and in PhoSim in some sort of version controlled way.

**Comment by tonytyson** [comment]
LCA-13381-A

**Comment by jchiang87** [comment]
It would be great if we could do what you propose @cwwalter .  I'm not totally convinced that segmentation.txt and focalplanelayout.txt are what we want, though.  I just used them for now because they were convenient and basically had the info I needed.

**Comment by cwwalter** [comment]
I think the issue of whether we can extract the sensor location / parameters from a database as opposed to the PhoSim text files as currently implemented can go into a separate issue.

For this issue we should concetrate on merging @jchiang87 code in branch

 https://github.com/LSSTDESC/imSim/tree/issue/6/realistic_electronics_chain

and adding bleeding as specified in issue #7.

Is that code still OK Jim?

**Comment by cwwalter** [comment]
@SimonKrughoff Would an issue to replace getting the focal plane layout position etc from a system database (now magicdraw?) instead of the PhoSim text files in the future be filed against obs_lsstSim?

**Comment by jchiang87** [comment]
@cwwalter The code needs some work before merging (apart from adding the bleeding stuff).  I've been neglecting it in favor of other work, so it would be good to have a time scale on which the code in that branch needs to be ready.

**Comment by cwwalter** [comment]
This is DC2 time scale.  So, we have to figure out the real schedule later but I'm thinking probably sometime in the fall.

**Comment by cwwalter** [comment]
The initial version of this by @jchiang87 has now been merged in PR #66.

**Comment by cwwalter** [comment]
@jchiang87 Where do we stand on this now given the PR#66 is merged?

**Comment by jchiang87** [comment]
I have code in https://github.com/LSSTDESC/imSim/tree/u/jchiang/set_noao_keywords to get the NOAO keywords correct so that mosaics in ds9 look right.   I don't think the `obs_` packages in the Stack care about these keywords, but I'm not sure.

At one of the sessions during the Stony Brook meeting, there was an expressed desire to agree on the electronics readout effects we want to include.  I'm open to having that discussion, but I'm not planning on organizing anything in the foreseeable future.

**Comment by cwwalter** [comment]
> At one of the sessions during the Stony Brook meeting, there was an expressed desire to agree on the electronics readout effects we want to include. I'm open to having that discussion, but I'm not planning on organizing anything in the foreseeable future.

So, let me try to summarize and make sure I understand.  After we merged #66 we can read the eimage file in with write_amp_image_file.py and write out "correct" amplifier output files that can be read by processsccd.

However, there are currently no sensor effects (BF, tree rings, CR, saturation) other than those due to electronics read out only.  Is that all right?

If so, maybe we should close this issue.

#7 already covers the sensor effects and then we could add a new issue on the mosaic display (or is that ready now?)

What do you think?

**Comment by jchiang87** [comment]
I had thought that someone mentioned an electronics readout effect that was not a sensor effect that this code does not simulate.   I don't remember what it was, however.   This code implements all of the readout effects that are completely specified in the segmentation.txt file that phosim uses (after correcting the pixel geometry to look like the actual devices).  As far as I am concerned, this issue can be closed.  If someone wants something else, a new issue can be opened.

**Comment by cwwalter** [comment]
Was it electronics based non-linearity/saturation or is that in segmentation.txt description?

I'll close this.  Can you add a new issue for the NOAO mosaic headers and possibly for the electronics effect?

**Comment by jchiang87** [comment]
Instead of creating a new issue for the NOAO keywords, I just made the PR on the branch.  You should be able to add it to the project board like that.   non-linearity isn't in the segmentation.txt description.  I'd prefer to hold off on creating a new issue for any readout related work until we know exactly what we want done.

**Comment by cwwalter** [comment]
OK got it thanks.

**Comment by cwwalter** [comment]
Oh, I remember now. I think it was bleed trails.  That happens on readout. Is that what you were thinking of?
