### ISSUE TITLE
Test imSim in the NERSC/Cori KNL partition

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#60]
This requires us first building the stack in the KNL partition.

We might not need to do this for DC2 given imSim computational requirements but there is a good chance much of our allocated resources will be on KNL so we should understand stack and imSim performance there.

**Comment by heather999** [comment]
Installed lsst_distrib w_2017_26 + lsst_sims sims_2_3_6 using external Anaconda 4.4.0 py3 + master of imSim
Ran nosetests using an interactive batch job on KNL:
```(IMSIM) heatherk@nid02306:/global/common/cori/contrib/lsst/lsstDM/knl-test/imSim_20170724/imSim> nosetests -w $SCRATCH/knl/imsim
..WARNING: ErfaWarning: ERFA function "taiutc" yielded 1 of "dubious year (Note 4)" [astropy._erfa.core]
WARNING: ErfaWarning: ERFA function "taiutc" yielded 1 of "dubious year (Note 4)" [astropy._erfa.core]
.........
----------------------------------------------------------------------
Ran 11 tests in 175.031s

**Comment by cwwalter** [comment]
I believe this is due to the fact that the year of of observation is outside of the range in the functions.  It is dubious :).  I remember looking into this before by reading those notes referenced.

**Comment by jchiang87** [comment]
Running imsim_deep_pipeline requires setting up on-disk catalogs of the four 10sq degree fields for DC1.  I'm on vacation this week, so wrangling imsim_deep_pipeline for KNL will probably take more cycles from me than I am willing to devote this week.    To move forward on these tests, I would just get some production phosim instance catalogs for single sensor-visits from Tom and see if you can run them in batch on KNL and do some timing comparisons with the corresponding phosim runs.

**Comment by heather999** [comment]
I ran ```imsim.py tiny_instcat.txt``` on KNL. imSim is now also set up for Haswell. After consulting with Richard & Tom - my current plans are to use the NERSC interactive partition to run a manageable test.. something that takes about an hour on Haswell and then re-run on KNL. I'm looking through the example catalogs provided by PhoSim and the DC1 set to see if I can tweak an input catalog that meets that constraint.
As you might have heard, James Perry is joining us to help out with running jobs at NERSC. This is an opportunity to get him involved and I'm hoping he'll be able to help out during my vacation.

**Comment by heather999** [comment]
dropping the contents of an email exchange in response to the status update posted: 
https://confluence.slac.stanford.edu/pages/viewpage.action?spaceKey=LSSTDESC&title=ImSim+on+KNL+at+NERSC

> Hi James,
> 
> Thanks for this. If I understand correctly, suppressing threading in the OpenBLAS library allows up to 48 ImSim processes to be run concurrently on a KNL node. The runtime for the 48-process run (1:24:24) is much less than what I would anticipate the time to be for 48, sequential runs -- that is 48×1:03.:15 = 50:36:00, so representing a potential speed-up of ~36 times.
> 
> Assuming that collections of ImSim runs take similar amounts of time to complete and consume similar amounts of memory to above, this seems a good, quick work-around to get better efficiency out of the KNL node.
> 
> Speak to you soon,
> George.
> 

Cc: DESC team.

--
Dr George Beckett,
University of Edinburgh

**Comment by heather999** [comment]
Dumping more from the same email thread:

> Seth Digel has machinery from the PhoSim studies to look at performance vs
> input sky…
> 
> Also, in terms of efficiency of KNL use, the goal is to be able to use as
> many of the threads on a node as possible, since the batch system requires
> us to reserve entire nodes.
> 
> Richard
>

**Comment by heather999** [comment]
and more..

> Hi Chris,
> 
> In principle you can use all 68. The problem that usually enters is the minimal amount of memory for each thread and thread contention on the on-chip interconnect (assuming threads are independent and no issues with locks).
> 
> Because the on-chip RAM is limited to 16GB, if you use all 68 cores, you have only 235MB/core. If you include the (slower) 96GB off-chip RAM, you have 1.65GB/core. If you require some minimum RAM/core that's larger than this number, then you have to use fewer cores or refactor the code.
> 
> The problem even with the 1.65GB/core number is that most codes are not sufficiently compute-intensive (not enough flops/byte ratio), so they will see the speed difference between the MCDRAM and the off-chip DRAM, lowering efficiency.
> 
> The other problem with the KNL is that, because of the lower clock rate and simpler cores, one loses a factor of 2-3 (should not be 8, that's what I was wondering) in performance wrt a Haswell core (we have seen this in multiple HPC codes), so unless you can vectorize a significant proportion of the compute (using AVX-512 on the KNL), you leave a lot of performance lying around on the table (potentially a factor of 8 from the vectorization alone).
> 
> Hope this helps,
> 
> Salman
> 
> 
> 
> On 9/11/17 9:24 AM, Chris Walter wrote:
> Hi Salman,
> 
> How many cores are in principle possible for us to use? I found this at NERSC:
> 
> “he Xeon-Phi “Knights-Landing” 7250 processors in Cori have 68 CPU cores where are organized into 34 “tiles" (each tile comprising two CPU cores and a shared 1MB L2 cache) which are placed in a 2D mesh, connected via an on-chip interconnect as shown in the following figure".
> 
> Is there a sort of “hyperthreading” going on here so we should perhaps use 34 or can we use all 68?
> 
> Thanks James!  From what Salman said in another meeting we were at the factor of 8 slow down sounds like it is too much.  Is there any sort of profiling we can do to try to pin down what is going on in terms of memory, startup time, or some particular library etc?
> 
> Thanks,
> 
> -Chris
>

**Comment by heather999** [comment]
Heather had wondered if running imSim via shifter image would improve the startup time.  Here is Mustafa's response:

> The startup time should be the same except for the minimal difference stdout, printing logs to the screen vs. buffering and then to a log file.

**Comment by heather999** [comment]
James P. has kindly provided an update on Confluence, he has asked for some guidance on how to proceed:
https://confluence.slac.stanford.edu/display/LSSTDESC/ImSim+on+KNL+at+NERSC#ImSimonKNLatNERSC-Current

**Comment by heather999** [comment]
Next steps discussed in Slack to run some test on Galsim:
https://lsstc.slack.com/archives/C2PNKDK97/p1505839072000411

**Comment by cwwalter** [comment]
What was the outcome of the KNL hack work? Is our performance on KNL now as expected.  Should we close this testing issue and open a new one if there are remaining KNL performance issues?

**Comment by jchiang87** [comment]
I think the main thing we (or at least I) learned from the KNL hack day was the reason for the ~6 slowdown on KNL rather than the anticipated ~2-3, namely non-mpi applications like imsim can only use the slower L3 cache rather than the faster L1 and L2 caches available to MPI jobs.

In other areas, the profiling we (mostly James) did showed that for typical DC1 fields, only about 6% of the time was spent in galsim's drawImage, the rest being used by lsst_sims code.  This seems like an area ripe for improvement, but the ratios of galsim vs lsst_sims code times will change with the sensor effects enabled.   Nevertheless, I think we've addressed the original intent of this issue, so I'm ok with closing it.
