### ISSUE TITLE
Produce multiple fits files if more than one snap is requested.

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#63]
After the fix to #62, if two snaps are requested the sky and sources will all be normalized by the total exposure time.

To better simulate the actual telescope output if multiple snaps are requested then a fits file should be produced for each snap.

**Comment by cwwalter** [comment]
@ksk Can you comment on the state of DM handling two snaps?  For DC2 should we just be sticking with 30 seconds?

I think we need to think about this carefully because, if we wanted to sa,y add and remove CRs, my understanding of the current algorithm is that is uses differencing.

**Comment by ksk** [comment]
You seem to have sent the message to the wrong account.

**Comment by cwwalter** [comment]
Dear Nakano-san,

Very sorry.  I meant to notify @SimonKrughoff who uses "ksk" in another system we use.  I hope you can just unsubscribe from this thread and we won't bother you any more.

Chris Walter
Duke University

**Comment by cwwalter** [comment]
I'm closing this for now as multiple snaps does not seem to be something we are even positive we will be doing.
