### ISSUE TITLE
Turn on Atmospheric Differential Chromatic Refraction

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#65]
We should at least add the option to turn this on and perhaps use it in DC2.  It exists already as an option in GalSim as implemented by @jmeyers314.  The code is here.

https://github.com/GalSim-developers/GalSim/blob/releases/1.4/galsim/dcr.py

**Comment by cwwalter** [comment]
@jmeyers314 In the FFT approach your dir option will turn this on.

How would this show up in the atmospheric ray tracing case?

**Comment by jmeyers314** [comment]
I'm assuming "dir option" is autocorrected "dcr option"?

Hmmm... That is an interesting question.  For most `ChromaticObject`s, I think they should be constructed and drawn the same way in both FFT and photon-shooting mode (except for the `method=...` part, of course).  I just tried this though and I see there's a bug when the number of photons at a given sample wavelength turns out to be zero (at least, I think that's the bug, I'm still investigating...).  Even if it did run though, I'm not convinced that the n_photons part is being properly handled in the chromatic case at the moment.  

The possible downside to using the existing `ChromaticObject.drawImage` is that it will only sample a discrete number of wavelengths, instead of sampling continuously from SED*Bandpass.  (I suppose there may be some sampling equivalent to the trapezoidal method of integration that we use for FFT-mode that would partially mitigate this?  Need to think...)

Once we're convinced that `ChromaticObject.drawImage(method='phot')` works, then adding DCR should look similar to what's in `ChromaticAtmosphere` now: https://github.com/GalSim-developers/GalSim/blob/master/galsim/chromatic.py#L1381.  I.e., a wavelength-dependent shift transformation.

**Comment by cwwalter** [comment]
> I'm assuming "dir option" is autocorrected "dcr option"?

Yes, sorry..

If one is really handling refraction due to different indices of refraction in the turbulent atmosphere, in principle you wouldn't need to add a shift right?  But, now the  initial rays are always considered at normal incidence correct?

**Comment by jmeyers314** [comment]
I'm not sure.  Certainly the turbulent atmospheric PSF stuff currently implemented doesn't know anything about the wavelength dependence of the refractive index.  It only knows about the spatial variation of refractive index.  I believe it's the relative scale and amplitude of this spatial variation to the particular wavelength being simulated that leads to chromatic seeing.  There may be a way to make DCR emerge more naturally by adding some kind of knowledge of incidence angle and dispersion to the turbulence simulation, but it's not obvious to me how to actually do that.  My intuition is that adding a chromatic shift is a reasonable approach though.

**Comment by cwwalter** [comment]
> My intuition is that adding a chromatic shift is a reasonable approach though.

Got it. Thanks.

**Comment by danielsf** [comment]
I know that Ian Sullivan wrote his own tool for simulating DCR while developing the DM tool to correct for DCR.  He might be worth speaking to, depending on how faithful we want our DCR simulations to be.

**Comment by cwwalter** [comment]
I have talked to Ian (he will report at the SSim meeting this week). The correction is not ready in DM.  So, we probably do not want this on in DC2.  We should check if there are groups (like SN) that would want it anyway.  I will file a general issue in the DC2 repo about this.

**Comment by cwwalter** [comment]
@jmeyers314 Can you just confirm one thing for me?  In the DFT case the code is dcr.py can already be called. Is that correct?

**Comment by jmeyers314** [comment]
>@jmeyers314 Can you just confirm one thing for me? In the DFT case the code in dcr.py can already be called. Is that correct?

I'd suggest using [ChromaticAtmosphere](https://github.com/GalSim-developers/GalSim/blob/releases/1.4/galsim/chromatic.py#L1009), which internally uses dcr.py, but yes, this should work for DFTs.  For photon shooting with a chromatic realistic atmospheric PSF, I think the easiest approach might be to add DCR as a surface_op in the draw stage.  That should be relatively straightforward to implement, I think.

**Comment by cwwalter** [comment]
In issue #28 in the DC2 Repo we decided we would in fact turn DCR on for DC2.  So, we need to apply this shift when we turn on the GalSim atmospheric raytracing.

**Comment by jmeyers314** [comment]
The DCR code in GalSim computes the absolute refraction (as a function of wavelength).  In the past, I've subtracted the absolute refraction of the filter central wavelength to narrow in on just differential chromatic refraction.  We could pretty easily turn this off though.  E.g., comment out [this line](https://github.com/GalSim-developers/GalSim/blob/releases/1.5/galsim/chromatic.py#L1396) (for DFT drawing).

**Comment by danielsf** [comment]
Right now, we use the LSST sims code to integrate the SED over the bandpass and find a flux for the object.  We pass that flux directly into GalSim to draw the image (so no, we don't use chromaticObject)

**Comment by cwwalter** [comment]
Hmm... OK right.

@danielsf So, I think this has an interesting consequence. It means that we can't use the same instance catalogs for the parametric and ray-traced atmospheres since one needs the refraction applied to the ICRS, and one doesn't. 

Do you agree?

I wonder what the best way to live with this is.    

- We could just accept/understand this.

- OTOH if the DCR code isn't doing more than the CatSim code we could have the option to tell GalSim not to apply it.  Sounds like a future error waiting to happen though...

**Comment by danielsf** [comment]
If you are planning to run ImSim both with and without DCR applied, that probably will imply difference InstanceCatalogs (unless DCR can be broken into a bulk shift and a wavelength-dependent delta added on top of that, then we might be able to make something work).

**Comment by cwwalter** [comment]
Adding a x-ref to the GalSim work on this.  https://github.com/GalSim-developers/GalSim/pull/961

Also, for the record since we are now using the exact same instance catalog as PhoSim with the PhoSim position convention, I think this means we have to have DCR turned in imSim.

**Comment by cwwalter** [comment]
GalSim-developers/GalSim#961 is now merged.  But this needs to be added to the surface operation list in imSim.

**Comment by cwwalter** [comment]
X-ref: The work to resolve this issue is in https://github.com/lsst/sims_GalSimInterface/pull/54

**Comment by cwwalter** [comment]
This issue closed by lsst/sims_GalSimInterface#54. Note currently DCR is only enabled when using the sensor model.  We will open an new issue for adding it when you aren't using sensors.
