### ISSUE TITLE
update imsim.py to use LSSTCameraWrapper

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/imSim#68]
This is related to the fixes discussed at https://github.com/LSSTDESC/SSim_DC1/issues/36

**Comment by jchiang87** [comment]
@heather999 Here's the relevant comment on the PR in `sims_GalSimInterface`:  https://github.com/lsst/sims_GalSimInterface/pull/32#issuecomment-329366702

Let me know if you have any questions.

**Comment by heather999** [comment]
slow to notice this @jchiang87, sorry, but I assume this still needs doing? Looking at that comment on the PR, am I incorrect to think this is just a simple one-liner?  It's a good way to get acquainted with the actual code :)
Testing using lsst_sims 2_3_7 might suffice?

**Comment by cwwalter** [comment]
Just pinging @danielsf since I thought the way he wound up changing things everything was already supposed to be consistent (but I want to check).

**Comment by jchiang87** [comment]
No, I had to incorporate these changes in the work on the shears.   I'm
about to do the PR for that this morning and will reference this issue.
Stay tuned.

On Oct 24, 2017 7:41 AM, "Chris Walter" <notifications@github.com> wrote:

Just pinging @danielsf <https://github.com/danielsf> since I thought the
way he wound up changing things everything was already supposed to be
consistent (but I want to check).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/LSSTDESC/imSim/issues/68#issuecomment-339013915>, or mute
the thread

**Comment by danielsf** [comment]
@heather999 Unfortunately, you are going to need the most up-to-date sims installation (2.4.0 or 2.4.1) to test this.  The underlying changes to sims_GalSimInterface do not exist in 2.3.7

**Comment by jchiang87** [comment]
Closed by #72
