### ISSUE TITLE
Make parameterized PSFs vary over the focal plane

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#70]
Currently (with a parameterized PSF) the PSF does not vary over the focal plane.

With the addition of #37 (passing the focal plane position to GalSim) this could be modified and a parameterized function could be used in GalSim.

On the other hand with a ray-traced atmosphere and an extra phase screen representing the perturbed optics (#9) I believe this would be naturally emergent.  So hopefully we get this in DC2 by implementing the other two options.

**Comment by jchiang87** [comment]
> With the addition of #37 (passing the focal plane position to GalSim) this could be modified and a parameterized function could be used in GalSim.

**Comment by cwwalter** [comment]
I think between #9 and #101 we now have a PSF which varies over the focal plane.

But we still might want to have this as a an option with parameterized PSFs (coupled with #37) so we could study PSF interpolation schemes as mentioned by Jim above.  So, am leaving this issue live but removing the DC2 label since I think we have implemented the feature there.

**Comment by cwwalter** [comment]
Hi All,

This is a very old issue and the way we do PSF and the work the PSF group is doing is quite a bit different now.

Is this sort of thing something that the PSF group would still be interested in?

**Comment by rmjarvis** [comment]
There are lots of ways in the config structure to have parameterized PSfs vary over the focal plane.  I don't think we need something specific to imSim about this.

**Comment by cwwalter** [comment]
OK closing.
