### ISSUE TITLE
Check lsst-galsim interface approach for off sensor bright objects.

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#73]
Both @jchiang87 and I remember @danielsf mentioning this was possible but we don't remember the details or if this is even correct.

Does this possibility exist now?

**Comment by danielsf** [comment]
For each chip on the focal plane, sims_GalSimInterface makes some arbitrary cut off representing "sources on the sky likely to illumine this chip."  It then simulates all of the objects in that region and keeps whatever photons land on the chip in question.  We could just increase the size of that region for bright sources.  This would not represent ghosts and glints and all of the other fancy optical effects that PhoSim can simulate.  It would just represent the effect of convolving a bright source with the PSF.

**Comment by cwwalter** [comment]
From talking to Scott with Jim in slack, it looks like this can work in a similar way to how PhoSim would handle it.  We need to decide generally whether we will do sensor trimming like we did in DC1 or try to ignore off sensor bright objects in both PhoSim and here in imSim.

Doing it as we did in DC1 requires no new work on the imSim side. @danielsf would need to comment but we would at least need some tuning to make this work in imSim. In both cases I'm still not sure positive how to make sure sometimes there aren't a few sensors around with only a couple of bright sources in them that we would need to exclude somehow.

**Comment by danielsf** [comment]
I thought the conclusion of our discussion was that ImSim already handles off-sensor bright objects.  What does "doing it as we did in DC1" mean?

**Comment by cwwalter** [comment]
> I thought the conclusion of our discussion was that ImSim already handles off-sensor bright objects. What does "doing it as we did in DC1" mean?

In DC1 what we did was not to trim the catalog, but to trim the sensors to be simulated before simulation. Humna prepared a list of which sensors to simulate.  

I just meant that if we did it like DC1 we would do this again (Humna would need to run her code) and imSim would need no modifications. If we do off sensor objects for both imSim and PhoSim we need to set this up and tune it, and make sure there are no extra sensors simulated.

**Comment by danielsf** [comment]
Okay.  I see what you are saying.

For what it is work, I do not think that adding off-sensor objects will pose a problem for ImSim.  The `allowed_chips` control forces ImSim to build a camera with only the chips you want to simulate in it.  That should work in concert with the way ImSim finds and simulates off-sensor bright sources to produce the behavior we want (simulating off-sensor bright objects without simulating unwanted sensors).

**Comment by cwwalter** [comment]
> For what it is work, I do not think that adding off-sensor objects will pose a problem for ImSim. The allowed_chips control forces ImSim to build a camera with only the chips you want to simulate in it. 

This is the part I am confused by, what we are talking about is just trimming the input catalog and then PhoSim has a command like:

> set PhoSim to only simulate sensors that have a minimum of ~100 objects on them (might have to tune that threshold)

So we don't have to know ahead of time what sensors to simulate.  If we are doing that we can just simulate the sensors we need like before.  Or am I misunderstanding what you are saying?

**Comment by danielsf** [comment]
No, you are not misunderstanding (I may have misunderstood the strategy we are adopting).

We would have to add the "only simulate chips with N sources on them" feature to ImSim.  That probably won't be too hard.

**Comment by cwwalter** [comment]
> We would have to add the "only simulate chips with N sources on them" feature to ImSim. That probably won't be too hard

OK. so we have to decide whether to use the strategy before or switch to this new mode and add that feature.  It's probably better to use the new mode since that was a lot of overhead last time by Eric, Humna, Seth and Tom etc but it would be good to know that this is something that actually works.

On the PhoSim side we have heard it will work; and for imSim we would need to add this feature to test.

**Comment by cwwalter** [comment]
I think this is ready.  Off-sensor sources work (as confirmed by @danielsf).  For the minsource equivalent @jchiang87 is implementing this as part of the DC2 workflow engine as a small c++ trim program.

If this is ready can you close this Jim?

**Comment by jchiang87** [comment]
Yes, I think we have what we need for this.
