### ISSUE TITLE
Produce calibration data products other than flats

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#74]
If we want to do BF corrections we will need calibration products.  Eventually we also want to drive other sensor validation tests so we may want a more generic solution.

**Comment by cwwalter** [comment]
I am renaming this issue to make it more general.  Since the instance catalog format is now set to be the same as PhoSim for at least run 2, this issue is to make sure we add any interface additions we need in imSim itself for producing calibration products.

There should be an issue in the DC2 repo to actually make them.

**Comment by cwwalter** [comment]
@jchiang87 sounds like you already are doing this and we now know how to make all the calibration products we need right?

**Comment by jchiang87** [comment]
Yes, I'm working on it now.  I've put the relevant scripts in https://github.com/LSSTDESC/desc_sim_utils/tree/u/jchiang/imsim_calib_scripts/bin.src
though I guess we might consider moving the imsim-specific ones to this repo.

**Comment by cwwalter** [comment]
OK thanks.  Since this issue  is about making sure we have the interfaces in places to create them in imSim (rather than actually making them). I'll close this.  

The actual production of all needed calibration products for 2.0i should be tracked in the DC2-production repo I think.
