### ISSUE TITLE
Give imSim the ability to call realistic galaxy morphologies.

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#79]
We want to generically add the hooks or flags to enable calling different realistic galaxy morphologies to imSim, but specifically in the beginning we would like to use the work that @EiffL is doing to build galaxy structure calling the random walk knot code that @esheldon built into GalSim.   This work is targeted for DC2 inclusion.

 @EiffL's work is now being documented in LSSTDESC/DC2_Repo#32.

**Comment by EiffL** [comment]
I have opened a pull request which aims at solving this issue (https://github.com/LSSTDESC/imSim/pull/89) by letting ImSim parse 'knots' components in the instance catalog, which are then drawn by the GalSim interface (https://github.com/lsst/sims_GalSimInterface/pull/40, https://github.com/lsst/sims_GalSimInterface/issues/39)

The format of the RandomWalk component in the instance catalog is identical to a normal Sersic profile, except the source type is coded as `knots` and the entry corresponding to `sindex` stores the number of knots.
I'm still doing some testing but it runs

**Comment by cwwalter** [comment]
Is the actual knot sequence unique to the galaxy or will it depend on the current state of the random number generator?

**Comment by EiffL** [comment]
Yes, it depends on the state of the random number generator.

**Comment by cwwalter** [comment]
I'm wondering if we shouldn't seed it with something like the galaxy ID. I'm thinking you might pull out just that line (or a subset of lines) to re-simulate them to see what is happening, and then of course whatever you are looking for won't be reproducible since the sequence will now be at a different place.

**Comment by EiffL** [comment]
yes, I think that's a very good solution. The random number generator can be specified to the RandomWalk GalSim object, I'll just pull the galaxyId and use it as you suggest.

**Comment by cwwalter** [comment]
> The format of the RandomWalk component in the instance catalog is identical to a normal Sersic profile, except the source type is coded as knots and the entry corresponding to sindex stores the number of knots.

I was looking at the code related to this.  I see that you set can set the extinction for the knots separately from the galaxies and it looks like if you don't set them the extinction would be zero.
Is that correct?

Is the knot flux you calculated before or after the extinction?    Depending on what you want, we might want to set those parameters to those already specified in the galaxy lines and never allow them to be set for the knots.  

I suppose one could make the same comment for the two normal components.  In any case, we at least might want to check/enforce consistency between the knots and the disk for the parameters that should be the same.

**Comment by EiffL** [comment]
Yes, that is correct, the extinction is set independently for the galaxy and knots at the imSim level, but at the instance creation level all the parameters from the disk (including SED and extinction) are inherited by the knots. The flux of the knots is computed as a fraction of the total disk flux before extinction, but the same extinction gets applied afterwards. 
The issue is that with the current catalog format, the only way to check for consistency at the imSim level would be to cross-match the sersic and knots catalogs by positions :-/ For a given galaxy, the disk, bulge and knots each have a different uniqueId. 

I do think it would make a lot of sense to have a galaxyId in the instance catalog, which would be shared by all the components (AGN, sersic, knots), but that would impact the phosim catalog format....

**Comment by danielsf** [comment]
During the phonecon last Friday, someone took it as an action item to investigate the datatype of the object IDs in PhoSim.  It is possible that PhoSim now treats the object IDs as strings, in which case we could use something like `1234_k1` to indicate the first knot in galaxy `1234`.  Even if that is not the case, we should be able to associate components of the same galaxy by taking `uniqueId//1024`.  `uniqueId` is calculated here

https://github.com/lsst/sims_catalogs/blob/master/python/lsst/sims/catalogs/definitions/InstanceCatalog.py#L696

where `self.db_obj.getObjectTypeId()` is just an int that is associated with each type of galaxy component (i.e. all bulges have the same `ObjectTypeId`, all disks have the same `ObjectTypeId`, and I assume all knots will as well).

Does this help?

**Comment by EiffL** [comment]
Yes, I forgot about that. Yes, so we can indeed add a consistency check, could be implemented in the `desc.imsim.validate_phosim_object_list()` function.

**Comment by cwwalter** [comment]
Closed by PR #89.
