### ISSUE TITLE
Add raytraced atmosphere

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#8]
Is there a GalSim issue for this yet?  @jmeyers314 will work on this at the hack day.

**Comment by cwwalter** [comment]
@jmeyers314 could you put a link in here to any issue/pr etc in the GalSim repo if and when one exists?
Thanks.

**Comment by cwwalter** [comment]
A pull request implementing the geometric part of the optics is now available from @jmeyers314 and in #GalSim-developers/GalSim/824.

**Comment by cwwalter** [comment]
@jmeyers314's code to do optical ray tracing in the atmosphere has now been merged to master.  However, there is currently no chromatic dependence in the PSF.  This may need to be hard-coded alá PhoSim.  But, we know that a simple lamba^(-0.2) response does not work for finite outer scales so we need to determine the correct form.

**Comment by jmeyers314** [comment]
Should note that the current implementation of atmospheric ray tracing only includes the so-called "first kick", and ignores any diffractive component (though initial studies indicate that the diffractive component may be well approximated by a simple obscured Airy function.)

**Comment by cwwalter** [comment]
@jmeyers314 Just checking in here for your thoughts on the current status of this feature relative to DC2. I think when we last heard from you there was discussion of the 2nd kick and whether it would be better to handle it as an Airy or if there was a closed form that would work.

I believe this should also be related to #65.

**Comment by jmeyers314** [comment]
@cwwalter, I think something like convolving by an Airy is probably our best bet (I have nothing new to say about the more mathy 2nd kicks).  

If we want something more precise, then one possibility may be to run a pilot job for each exposure that produces (a few) FFT-based PSFs, and a few corresponding raytraced-atmosphere-convolved-with-Airy PSFs, and then solves for any additional Gaussian convolution kernel that would bring the latter into agreement with the former.  (I think this ought to be fast enough.  How many total exposures is DC2?)  We could then use Convolve(raytraced-atmosphere, Airy, Gaussian matching kernel) for the actual exposure.  

TBH, I'm actually more worried about how this will get integrated into ImSim, especially chromatically, given that GalSim still doesn't have chromatic photon shooting.

**Comment by cwwalter** [comment]
> TBH, I'm actually more worried about how this will get integrated into ImSim, especially chromatically, given that GalSim still doesn't have chromatic photon shooting.

Hmm... OK @rmjarvis could you comment on this?  I think we have to decide really soon now whether it is in fact feasible to use this feature in DC2. 

@jmeyers314 can you say a bit more about not having more to say about the 2nd kick? I remember when you left off there were some numerical issues near the core that you were thinking about how to handle.  The pilot job idea is interesting but I'm wondering what is different compared to what is in PhoSim.  Is there a reason that technique won't work for us, or did you find an issue? I know you talked about this before but I don't think I ever really understood the conclusion.

**Comment by rmjarvis** [comment]
> TBH, I'm actually more worried about how this will get integrated into ImSim, especially chromatically, given that GalSim still doesn't have chromatic photon shooting.

I think for DC2 we decided that the mean color effect for a given band is good enough.  So we can just use the median wavelength of the band for lambda and not try to do proper chromatic shooting.  So if we can get a decent estimate of the extra Gaussian to apply for the second kick, we just do that and use achromatic photon shooting.

Is there something I'm missing Josh?  Some reason why this would be difficult to apply in imsim?

**Comment by jmeyers314** [comment]
Quick update.  I think I may have something reasonable for the second kick worked out now.  The issue that was previously holding me up was my desire to cleanly separate the atmospheric and optical PSFs.  However, the integrals in the second kick maths get much easier to evaluate if you let the Airy profile be part of the second kick.  (Basically the Airy optical transfer function has hard cutoff in k-space, so keeping it around means you never have to integrate out to k=infinity).

Here's a plot showing the effects of choosing different scales for where to divide the PSF into a "first kick" and "second kick".  (The cutoff is listed on the tops of the columns.)  The first kick includes all phase fluctuation scales up to the cutoff, and the second kick is a analytic integral accounting for the scales above the cutoff, and the Airy profile.  The numbers inset in each postage stamp indicate the HSM-measured sqrt(second moment) size for each blob.

![kcrit](https://user-images.githubusercontent.com/3650485/35466616-2f049f22-02ba-11e8-84dc-d450233c4407.png)

In the above, you can see that that for a cutoff around 1, the DFT (i.e., full slow simulation) size in the first row agrees pretty well with the geometric approximation (combination of 1st and 2nd kicks) size in the last row.  I've tried a few different parameter settings (varying r0, wavelength, L0), and the appropriate cutoff scale seems fairly consistently around ~1, except for when I take the wavelength down to 350nm, in which case the appropriate cutoff seems closer to 0.1.  I'll have to run more of these to get statistics.

I'll also try running with some hand-tuned cutoff scales at NERSC, where I have a bunch of DFT PSFs to compare against and report back.  

I think one of two things will likely emerge as I gather more data.  1) The cutoff scale is fairly predictable given parameters, in which case we just use it.  2) The cutoff scale is hard to predict, in which case a pilot job to determine the cutoff scale might be needed.
