### ISSUE TITLE
Allow imSim to use images for sources

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#83]
We should extend the imSim interface to leverage the GalSim source functionality so we can draw images from postage stamps.

This has many possible applications but it is will be particularly useful to mix real images into to parameterized galaxy sources in large instance catalogs.

There is a specific request (from Nicola Napolitano) to add static lenses (like Einstein rings) to the simulation and this could be used to implement that.  For this lensing case we might also imagine letting imSim/GalSim generate these sources programmatically but this functionality will be useful in anywise.

We will need to extend the parser and have it be able to find the postage stamps.  This should be kept in mind when the work on #71 commences.

**Comment by cwwalter** [comment]
Pinging @rmjarvis to let him know this issue already exists (it came up in a meeting the other day).

Since this time we also know the lensed AGN and SN people want this functionality.  We could use GalSim's InterpolatedImage class.

**Comment by cwwalter** [comment]
Is the structure for what the image input files are going to look like and where they are going to live for the static lenses defined yet for DC2?  

If we are trying to match PhoSim instance catalogs it looks like we need a FITS datatype. Is the CatSim code for making these files already written or are we waiting for other work?

**Comment by danielsf** [comment]
There is currently no CatSim code for creating InstanceCatalogs that use FITS images as inputs.  It should not take much work to implement that, though.  Really the only question is, as you say, "where are we going to store the FITS files?"

**Comment by cwwalter** [comment]
@danielsf Where is the work happening (is there a repo) for the people planning on adding the static lenses?  Are they still on track planning on trying this for Run2.0?  There are several sprinkler and lens issues in the DC2 repo, so I'm not sure which it is. Is it number 40?

**Comment by jchiang87** [comment]
Here is the relevant PR for adding the static lenses for DC2:
https://github.com/LSSTDESC/sims_GCRCatSimInterface/pull/42
Finishing the review for that has been on my to-do list for a while.

**Comment by cwwalter** [comment]
Following up on this.  It seems this work is not quite done so we don't know (For example) where the images will be stored.  But, we will want this before 2.0 since it sounds like the static lenses will be ready at that point.

**Comment by cwwalter** [comment]
So all of the postage stamps that could be used in any visit, all in directory right?

**Comment by cwwalter** [comment]
This work is being implemented in #139 (and the associated https://github.com/lsst/sims_GalSimInterface/pull/57).
