### ISSUE TITLE
enable reading of gzipped instance catalog components and includeobj entries

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/imSim#96]
This will be more consistent with phosim behavior and will make the code to write instance catalogs for both imsim and phosim simpler.

**Comment by cwwalter** [comment]
How do you see this interacting with #71?

**Comment by jchiang87** [comment]
I think getting imsim able to read the same format files as phosim wrt gzipped files and `includeobj` is a more pressing concern than the work in #71.   Adding the desired functionality here will result in much less work in instance catalog generation code.  #71 isn't as relevant.

**Comment by cwwalter** [comment]
For future reference for people this issue (raised by Tom, answered by John) has an explicit description of the functionality.

https://bitbucket.org/phosim/phosim_release/issues/6/problem-interpreting-gzipped-instance
